// Scaffolding: CLI, REPL, tool registry, main entry point. Attendees do not edit this file.

import OpenAI from "openai";
import { randomUUID } from "crypto";
import * as fs from "fs";
import * as path from "path";
import { createInterface } from "readline";
import { fileURLToPath } from "url";
import {
  buildSystemPrompt,
  handleTurn,
  loadInstructions,
  discoverSkills,
  discoverCommands,
  executeCommand,
  measureContext,
  formatConversationForCompaction,
  applyCompaction,
  shouldAutoCompact,
  saveSession,
  loadSession,
  loadPastSessionSummaries,
  extractMemories,
  loadMemories,
  executeReadFile,
  executeShell,
  executeEditFile,
  executeListFiles,
  executeWebFetch,

} from "./exercises.js";
import {
  executeWriteFile,
  executeMessageUser,
  executeAskUser,
  executeReadBoard,
  executeUpdateBoard,
  getEnabledTools,
  ReadFileParams,
  ShellParams,
  EditFileParams,
  ListFilesParams,
  WebFetchParams,
  MessageUserParams,
  AskUserParams,
  ReadBoardParams,
  UpdateBoardParams,
  WriteFileParams,
  type Tool,
  type ToolName,
} from "./tools.js";
import {
  resolveConfig,
  parseCliConfig,
  type AgentConfig,
  type RequestedMode,
} from "./config.js";
import type { ChatProvider, Conversation } from "./conversation.js";
import { createConversation } from "./conversation.js";
import { Terminal, type TerminalOutput } from "./terminal.js";
import { exitGate } from "./exercises.js";
import type { ToolDecorator } from "./decorators.js";

function createLogger(verbose: boolean): (msg: string) => void {
  return verbose
    ? (msg: string) => process.stderr.write(msg + "\n")
    : () => { };
}

type CommandResult =
  | { type: "quit" }
  | { type: "compact"; summary: string }
  | { type: "custom"; response: string }
  | { type: "unknown"; name: string };

function isCommand(input: string): boolean {
  return input.startsWith("/");
}

function loadCompactionPrompt(): string {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);
  const promptPath = path.resolve(__dirname, "../../compaction-prompt.txt");
  return fs.readFileSync(promptPath, "utf-8");
}

async function handleCommand(
  input: string,
  provider: ChatProvider,
  conversation: Conversation,
  config: AgentConfig,
  sessionId: string,
): Promise<CommandResult> {
  const name = input.slice(1).trim().split(/\s+/)[0] ?? "";

  if (name === "quit" || name === "exit") {
    return { type: "quit" };
  }

  if (name === "compact") {
    const compactableText = formatConversationForCompaction(conversation);
    const template = loadCompactionPrompt();
    const pastSummaries = await loadPastSessionSummaries(config.historyDir ?? "", sessionId, provider);
    const prompt = template
      .replace("{{CONVERSATION}}", compactableText)
      .replace("{{PAST_SESSIONS}}", pastSummaries ? `Previous sessions:\n${pastSummaries}\n\n` : "");

    const summary = await provider([
      { role: "user", content: prompt },
    ]);

    return { type: "compact", summary };
  }

  const commands = config.commandsDir ? discoverCommands(config.commandsDir) : [];
  const matched = commands.find((c) => c.name === name);
  if (matched) {
    const args = input.slice(1).trim().slice(name.length).trim();
    const prompt = executeCommand(matched, args);
    const response = await provider([{ role: "user", content: prompt }]);
    return { type: "custom", response };
  }

  return { type: "unknown", name };
}

const tools: Tool[] = [
  { name: "read_file", description: "Read the entire contents of a file at the given path. This tool does NOT support pagination, line ranges, or partial reads — it always returns the whole file. Do not pass start, end, line_start, line_end, offset, or limit; the only parameter is path.", schema: ReadFileParams, execute: executeReadFile },
  { name: "write_file", description: "Write content to a file at the given path", schema: WriteFileParams, execute: executeWriteFile },
  { name: "edit_file", description: "Edit a file by replacing old_text with new_text within the specified line range. The file is unmodified if old_text is not found in the range.", schema: EditFileParams, execute: executeEditFile },
  { name: "shell", description: "Execute a shell command and return its output", schema: ShellParams, execute: executeShell },
  { name: "list_files", description: "Recursively list files and directories at the given path up to a maximum depth. Returns paths relative to the given directory.", schema: ListFilesParams, execute: executeListFiles },
  { name: "web_fetch", description: "Fetch the contents of a URL and return the response body as text", schema: WebFetchParams, execute: executeWebFetch },
  { name: "message_user", description: "Deliver your final response to the user. Use this when the task is complete.", schema: MessageUserParams, execute: executeMessageUser },
  { name: "ask_user", description: "Ask the user a question and wait for their response. Use at review gates when human input is needed before continuing.", schema: AskUserParams, execute: executeAskUser },
  { name: "read_board", description: "Read the current state of the kanban board. Returns the board JSON showing phase statuses and artifacts.", schema: ReadBoardParams, execute: executeReadBoard },
  { name: "update_board", description: "Update a phase on the kanban board. Changes the status and optionally records the artifact path.", schema: UpdateBoardParams, execute: executeUpdateBoard },
];

function parseFilePrompts(content: string): string[] {
  return content
    .split(/^---$/m)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

async function main(): Promise<void> {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    process.stderr.write("Set OPENROUTER_API_KEY environment variable\n");
    process.exit(1);
  }

  const client = new OpenAI({
    apiKey,
    baseURL: "https://openrouter.ai/api/v1",
  });

  const parsedCli = parseCliConfig(process.argv);
  if (typeof parsedCli === "string") {
    process.stderr.write(parsedCli + "\n");
    process.exit(1);
  }
  const { config: overrides, configFile, requestedMode, resumeSessionId } = parsedCli;
  const config = resolveConfig({ ...configFile, ...overrides });
  if (resumeSessionId && !config.historyDir) {
    throw new Error("--resume requires --history-dir");
  }
  const sessionId = resumeSessionId ?? randomUUID();
  const log = createLogger(config.verbose);
  const enabledTools = getEnabledTools(config, tools);

  const provider: ChatProvider = async (messages) => {
    const response = await client.chat.completions.create({
      model: config.model,
      messages: messages as OpenAI.Chat.ChatCompletionMessageParam[],
      temperature: config.temperature,
      max_tokens: 4096,
    });
    return response.choices[0]?.message?.content ?? "";
  };

  const filePath = requestedMode.type === "file" ? requestedMode.path : undefined;
  const interactive = requestedMode.type === "interactive"
    || (requestedMode.type === "auto" && process.stdin.isTTY);

  const resumedConversation = resumeSessionId
    ? loadSession(config.historyDir!, resumeSessionId)
    : null;
  if (resumeSessionId && !resumedConversation) {
    throw new Error(`Session not found: ${resumeSessionId}`);
  }
  if (resumedConversation) {
    log(`Resumed session ${sessionId} with ${resumedConversation.turns.length} turns`);
  }
  const conversation = createConversation(buildSystemPrompt(config, enabledTools, interactive));
  if (resumedConversation) {
    conversation.turns = resumedConversation.turns;
  }

  const instructions = loadInstructions(config.workDir, config.instructions);
  const skills = discoverSkills(config.skillsDir);
  const memories = loadMemories(config.workDir);

  let contextSections = "";
  if (instructions) contextSections += "\n\n## Project Instructions\n\n" + instructions;
  if (skills.length > 0) {
    contextSections += "\n\n## Available Skills\n\n" + skills.map((s) => `- ${s.name}: ${s.description}`).join("\n");
  }
  if (memories) contextSections += "\n\n## Things I remember from previous conversations\n\n" + memories;
  if (contextSections) {
    conversation.system += contextSections;
  }

  function writeProtocolOutput(content: string, toolCalls: ToolName[] = []) {
    if (config.outputFormat === "text") {
      process.stdout.write(content + "\n");
    } else {
      process.stdout.write(JSON.stringify({ content, tool_calls: toolCalls }) + "\n");
    }
  }

  async function processMessage(
    userContent: string,
    terminal?: TerminalOutput,
  ): Promise<boolean> {
    if (isCommand(userContent)) {
      const cmdResult = await handleCommand(userContent, provider, conversation, config, sessionId);

      switch (cmdResult.type) {
        case "quit":
          if (terminal) {
            terminal.goodbye();
          } else {
            writeProtocolOutput("goodbye.");
          }
          return false;
        case "compact": {
          const before = conversation.turns.length + 1;
          applyCompaction(conversation, cmdResult.summary);
          const after = conversation.turns.length + 1;
          if (terminal) {
            terminal.toolResult({ ok: true, output: `Compacted ${before} messages → ${after} messages` });
          } else {
            writeProtocolOutput(`Compacted ${before} messages → ${after} messages`);
          }
          break;
        }
        case "custom":
          if (terminal) terminal.answer(cmdResult.response);
          break;
        case "unknown":
          if (terminal) {
            terminal.error(`Unknown command: /${cmdResult.name}`);
          } else {
            writeProtocolOutput(`Unknown command: /${cmdResult.name}`);
          }
          break;
      }
      return true;
    }

    let augmentedContent = userContent;
    if (config.inputFiles.length > 0) {
      const sections: string[] = [];
      for (const filePat of config.inputFiles) {
        const resolved = path.isAbsolute(filePat) ? filePat : path.resolve(config.workDir, filePat);
        const dir = path.dirname(resolved);
        const base = path.basename(resolved);
        let files: string[];
        if (base.includes("*")) {
          if (!fs.existsSync(dir)) { files = []; }
          else {
            const escaped = base.replace(/[.+?^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*");
            const pattern = new RegExp("^" + escaped + "$");
            files = fs.readdirSync(dir).filter(f => pattern.test(f)).sort().map(f => path.join(dir, f));
          }
        } else {
          files = [resolved];
        }
        for (const f of files) {
          if (fs.existsSync(f) && fs.statSync(f).isFile()) {
            sections.push(`--- ${path.basename(f)} ---\n${fs.readFileSync(f, "utf-8")}`);
          }
        }
      }
      if (sections.length > 0) {
        augmentedContent = sections.join("\n\n") + "\n\n" + userContent;
      }
    }

    const decorators: ToolDecorator[] = [];
    if (config.exitGates.length > 0) decorators.push(exitGate(config.exitGates));
    const result = await handleTurn(provider, conversation, augmentedContent, config, enabledTools, terminal, decorators);

    const usage = measureContext(
      conversation.system,
      conversation,
      enabledTools,
      config.maxContextChars,
    );

    if (shouldAutoCompact(usage)) {
      const compactText = formatConversationForCompaction(conversation);
      const template = loadCompactionPrompt();
      const pastSummaries = await loadPastSessionSummaries(config.historyDir ?? "", sessionId, provider);
      const compactPrompt = template
        .replace("{{CONVERSATION}}", compactText)
        .replace("{{PAST_SESSIONS}}", pastSummaries ? `Previous sessions:\n${pastSummaries}\n\n` : "");
      const summary = await provider([{ role: "user", content: compactPrompt }]);
      applyCompaction(conversation, summary);
      log("Auto-compacted conversation (context budget exceeded)");
    }

    if (config.historyDir) {
      saveSession(config.historyDir, sessionId, conversation);
    }

    try {
      await extractMemories(provider, userContent, result.content, config.workDir);
    } catch { }

    if (!terminal) {
      writeProtocolOutput(result.content, result.toolCalls);
    }

    if (config.outputFile) {
      const outputDir = path.dirname(config.outputFile);
      if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });
      fs.writeFileSync(config.outputFile, result.content + "\n");
    }

    return true;
  }

  if (filePath) {
    const content = fs.readFileSync(filePath, "utf-8");
    const prompts = parseFilePrompts(content);
    for (const prompt of prompts) {
      log(`\n=== File prompt: ${prompt.slice(0, 80)}${prompt.length > 80 ? "..." : ""} ===`);
      const shouldContinue = await processMessage(prompt);
      if (!shouldContinue) break;
    }
  } else if (interactive) {
    const terminal = new Terminal();
    const toolNames = enabledTools.filter((t) => t.name !== "message_user").map((t) => t.name);
    terminal.banner(config.model, toolNames);

    const rl = createInterface({ input: process.stdin, output: process.stdout });
    const PROMPT = terminal.promptString();
    const CONTINUATION = "  ";
    let closed = false;
    rl.on("close", () => { closed = true; });
    rl.setPrompt(PROMPT);
    rl.prompt();

    let buffer = "";

    for await (const line of rl) {
      if (line.endsWith("\\")) {
        buffer += line.slice(0, -1) + "\n";
        rl.setPrompt(CONTINUATION);
        rl.prompt();
        continue;
      }

      const userContent = (buffer + line).trim();
      buffer = "";
      rl.setPrompt(PROMPT);

      if (!userContent) {
        rl.prompt();
        continue;
      }

      const shouldContinue = await processMessage(userContent, terminal);
      if (!shouldContinue || closed) break;
      console.log();
      rl.prompt();
    }
    terminal.goodbye();
  } else {
    const rl = createInterface({ input: process.stdin });

    for await (const line of rl) {
      let userContent: string;
      if (config.inputFormat === "text") {
        userContent = line;
      } else {
        try {
          const parsed = JSON.parse(line);
          userContent = typeof parsed.content === "string" ? parsed.content : line;
        } catch {
          userContent = line;
        }
      }

      const shouldContinue = await processMessage(userContent);
      if (!shouldContinue) break;
    }
  }
}

export {
  tools,
  isCommand,
  handleCommand,
  parseFilePrompts,
  main,
};
