// Scaffolding: AgentConfig type, CLI parsing, defaults, resolution. Attendees do not edit this file.

import type { ToolName, ToolSelection } from "./tools.js";
import { TOOL_NAMES } from "./tools.js";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

/**
 * Configuration for an agent instance. Controls model, tools, prompt,
 * iteration budget, and working directory. The same codebase can run
 * different agents (worker, judge, orchestrator) by varying the config.
 */
export type AgentConfig = {
  // Module 01: Foundations
  model: string;
  systemPrompt: string;
  rolePrompt: string | null;
  tools: ToolSelection;
  workDir: string;
  verbose: boolean;
  maxIterations: number;
  temperature: number;
  // Module 02: Context Engineering
  instructions: string | null;
  skillsDir: string | null;
  historyDir: string | null;
  commandsDir: string | null;
  maxContextChars: number | null;
  // Module 03: Guardrails and Safety
  allowTools: string[];
  denyTools: string[];
  protectedFiles: string[];
  secretPatterns: string[];
  auditLog: string | null;
  sandboxVm: boolean;
  // Workflow integration
  inputFiles: string[];
  outputFile: string | null;
  inputFormat: "json" | "text";
  outputFormat: "json" | "text";
  // Decorator routing: when set, AgentState.currentPhase observed by every
  // decorator's appliesTo equals this value. When unset, falls back to
  // basename-of-rolePrompt (legacy behavior). Callers that drive runPhase
  // with materialized inline role-prompt files MUST set this so phase-scoped
  // decorators fire.
  currentPhase: string | null;
  // Exit gates: shell commands that must each exit 0 before the agent is
  // allowed to terminate via `message_user`. Used by harnesses like
  // workflow drivers to enforce "tsc passes, tests pass, rubric passes" without
  // relying on the LLM to follow instructions in the prompt. Each command
  // runs in `workDir` via `sh -c`; a non-zero exit becomes a Deny on
  // message_user (the LLM sees the gate's stderr/stdout + exit code and
  // gets another turn to fix the underlying failure).
  exitGates: string[];
};

export type RequestedMode =
  | { type: "auto" }
  | { type: "interactive" }
  | { type: "protocol" }
  | { type: "file"; path: string };

// Broad default heuristics for credential detection, not an exhaustive scanner.
// Only used when the caller does not provide custom patterns via config.
export const DEFAULT_SECRET_PATTERNS = [
  "(?i)api[_-]?key\\s*[:=]\\s*\\S+",
  "(?i)secret\\s*[:=]\\s*\\S+",
  "(?i)password\\s*[:=]\\s*\\S+",
  "(?i)token\\s*[:=]\\s*\\S+",
  "sk-[a-zA-Z0-9]{20,}",
  "ghp_[a-zA-Z0-9]{36,}",
];

// Prompt paths resolve from the source directory via import.meta.url (ESM idiom).
// Rust uses CARGO_MANIFEST_DIR; Scala uses cwd. Each is the idiomatic way to find
// source-relative assets in that runtime. The converged contract: fail fast if missing.
//
// resolvePromptPath tries multiple locations so the agent works in:
//   1. Workshop layout — agent/ts/src/ ⇒ ../../system-prompt.txt under agent/
//   2. Copied/standalone layout — agent_root/src/ ⇒ ../system-prompt.txt
//   3. Bundled layout — agent_root/src/system-prompt.txt
// Falls back to (1) (the canonical workshop path) if nothing exists, so failure
// surfaces as a readable "ENOENT: ../../system-prompt.txt" rather than silent.
export function resolvePromptPath(srcDir: string, name: string): string {
  const candidates = [
    path.resolve(srcDir, "../..", name),
    path.resolve(srcDir, "..", name),
    path.resolve(srcDir, name),
  ];
  for (const c of candidates) {
    if (fs.existsSync(c)) return c;
  }
  return candidates[0];
}

export function defaultConfig(): AgentConfig {
  const srcDir = path.dirname(fileURLToPath(import.meta.url));
  return {
    model: process.env.MODEL ?? "anthropic/claude-sonnet-4",
    systemPrompt: resolvePromptPath(srcDir, "system-prompt.txt"),
    rolePrompt: null,
    tools: { type: "all" },
    workDir: process.cwd(),
    verbose: false,
    maxIterations: 20,
    temperature: 0,
    instructions: null,
    skillsDir: null,
    historyDir: null,
    commandsDir: null,
    maxContextChars: null,
    allowTools: [],
    denyTools: [],
    protectedFiles: [],
    secretPatterns: [...DEFAULT_SECRET_PATTERNS],
    auditLog: null,
    sandboxVm: false,
    inputFiles: [],
    outputFile: null,
    inputFormat: "json",
    outputFormat: "json",
    currentPhase: null,
    exitGates: [],
  };
}

export function loadConfigFile(filePath: string): Partial<AgentConfig> {
  const parsed = JSON.parse(fs.readFileSync(filePath, "utf-8")) as unknown;
  if (typeof parsed !== "object" || parsed === null) {
    return {};
  }

  const raw = parsed as Record<string, unknown>;
  const result: Partial<AgentConfig> = {};

  // Resolve relative paths in the config file against the config file's directory,
  // not CWD. This is the standard behavior for config files (like tsconfig.json).
  const configDir = path.dirname(path.resolve(filePath));
  const resolveConfigPath = (value: string): string =>
    path.isAbsolute(value) ? value : path.resolve(configDir, value);

  const maybeString = (value: unknown): string | undefined =>
    typeof value === "string" ? value : undefined;
  const maybePath = (value: unknown): string | undefined =>
    typeof value === "string" ? resolveConfigPath(value) : undefined;
  const maybePathOrNull = (value: unknown): string | null | undefined => {
    if (value === null) return null;
    return maybePath(value);
  };
  const maybeNumber = (value: unknown): number | undefined =>
    typeof value === "number" ? value : undefined;
  const maybeStringArray = (value: unknown): string[] | undefined =>
    Array.isArray(value) && value.every((item) => typeof item === "string")
      ? value as string[]
      : undefined;
  const assignIfDefined = <K extends keyof AgentConfig>(key: K, value: AgentConfig[K] | undefined): void => {
    if (value !== undefined) {
      result[key] = value;
    }
  };

  assignIfDefined("model", maybeString(raw.model));
  assignIfDefined("systemPrompt", maybePath(raw.systemPrompt));
  assignIfDefined("rolePrompt", maybePathOrNull(raw.rolePrompt));
  assignIfDefined("workDir", maybePath(raw.workDir));
  assignIfDefined("verbose", raw.verbose === true ? true : undefined);
  assignIfDefined("maxIterations", maybeNumber(raw.maxIterations));
  assignIfDefined("temperature", maybeNumber(raw.temperature));
  assignIfDefined("maxContextChars", maybeNumber(raw.maxContextChars));

  assignIfDefined("instructions", maybePathOrNull(raw.instructions));
  assignIfDefined("skillsDir", maybePathOrNull(raw.skillsDir));
  assignIfDefined("historyDir", maybePathOrNull(raw.historyDir));
  assignIfDefined("commandsDir", maybePathOrNull(raw.commandsDir));
  assignIfDefined("auditLog", maybePathOrNull(raw.auditLog));

  assignIfDefined("allowTools", maybeStringArray(raw.allowTools));
  assignIfDefined("denyTools", maybeStringArray(raw.denyTools));
  assignIfDefined("protectedFiles", maybeStringArray(raw.protectedFiles));
  assignIfDefined("secretPatterns", maybeStringArray(raw.secretPatterns));

  const maybePathArray = (value: unknown): string[] | undefined =>
    Array.isArray(value) && value.every((item) => typeof item === "string")
      ? (value as string[]).map(resolveConfigPath)
      : undefined;
  assignIfDefined("inputFiles", maybePathArray(raw.inputFiles));
  assignIfDefined("outputFile", maybePathOrNull(raw.outputFile));
  assignIfDefined("exitGates", maybeStringArray(raw.exitGates));
  if (raw.inputFormat === "json" || raw.inputFormat === "text") assignIfDefined("inputFormat", raw.inputFormat);
  if (raw.outputFormat === "json" || raw.outputFormat === "text") assignIfDefined("outputFormat", raw.outputFormat);

  if ("tools" in raw) {
    const names = maybeStringArray(raw.tools);
    if (names) {
      const parsedToolNames = parseToolNames(names.join(","));
      if (typeof parsedToolNames !== "string") {
        result.tools = parsedToolNames.length > 0
          ? { type: "only", tools: parsedToolNames }
          : { type: "all" };
      }
    }
  }

  return result;
}

export function parseCliConfig(argv: string[]): string | {
  config: Partial<AgentConfig>;
  configFile?: Partial<AgentConfig>;
  requestedMode: RequestedMode;
  resumeSessionId?: string;
} {
  const config: Partial<AgentConfig> = {};
  let configFile: Partial<AgentConfig> | undefined;
  let requestedMode: RequestedMode = { type: "auto" };
  let resumeSessionId: string | undefined;
  let modeFlag: "--file" | "--interactive" | "--protocol" | null = null;

  function readFlagValue(flag: string, index: number): string | { error: string } {
    if (index >= argv.length) return { error: `${flag} requires a value` };
    return argv[index];
  }

  function setMode(nextFlag: "--file" | "--interactive" | "--protocol", mode: RequestedMode): string | undefined {
    if (modeFlag !== null) {
      return `Conflicting mode flags: ${modeFlag} and ${nextFlag}`;
    }
    modeFlag = nextFlag;
    requestedMode = mode;
    return undefined;
  }

  for (let i = 2; i < argv.length; i++) {
    switch (argv[i]) {
      case "--config": {
        const value = readFlagValue("--config", ++i);
        if (typeof value !== "string") return value.error;
        configFile = loadConfigFile(value);
        break;
      }
      case "--model": {
        const value = readFlagValue("--model", ++i);
        if (typeof value !== "string") return value.error;
        config.model = value;
        break;
      }
      case "--prompt": {
        const value = readFlagValue("--prompt", ++i);
        if (typeof value !== "string") return value.error;
        config.systemPrompt = value;
        break;
      }
      case "--role-prompt": {
        const value = readFlagValue("--role-prompt", ++i);
        if (typeof value !== "string") return value.error;
        config.rolePrompt = value;
        break;
      }
      case "--tools": {
        const value = readFlagValue("--tools", ++i);
        if (typeof value !== "string") return value.error;
        const parsedTools = parseToolNames(value);
        if (typeof parsedTools === "string") return parsedTools;
        config.tools = { type: "only", tools: parsedTools };
        break;
      }
      case "--work-dir": {
        const value = readFlagValue("--work-dir", ++i);
        if (typeof value !== "string") return value.error;
        config.workDir = value;
        break;
      }
      case "--verbose": {
        config.verbose = true;
        break;
      }
      case "--max-iterations": {
        const value = readFlagValue("--max-iterations", ++i);
        if (typeof value !== "string") return value.error;
        const parsedValue = Number(value);
        if (!Number.isInteger(parsedValue)) return `Invalid value for --max-iterations: ${value}`;
        config.maxIterations = parsedValue;
        break;
      }
      case "--temperature": {
        const value = readFlagValue("--temperature", ++i);
        if (typeof value !== "string") return value.error;
        const parsedValue = Number(value);
        if (isNaN(parsedValue)) return `Invalid value for --temperature: ${value}`;
        config.temperature = parsedValue;
        break;
      }
      case "--instructions": {
        const value = readFlagValue("--instructions", ++i);
        if (typeof value !== "string") return value.error;
        config.instructions = value;
        break;
      }
      case "--skills-dir": {
        const value = readFlagValue("--skills-dir", ++i);
        if (typeof value !== "string") return value.error;
        config.skillsDir = value;
        break;
      }
      case "--history-dir": {
        const value = readFlagValue("--history-dir", ++i);
        if (typeof value !== "string") return value.error;
        config.historyDir = value;
        break;
      }
      case "--resume": {
        const value = readFlagValue("--resume", ++i);
        if (typeof value !== "string") return value.error;
        resumeSessionId = value;
        break;
      }
      case "--commands-dir": {
        const value = readFlagValue("--commands-dir", ++i);
        if (typeof value !== "string") return value.error;
        config.commandsDir = value;
        break;
      }
      case "--max-context-chars": {
        const value = readFlagValue("--max-context-chars", ++i);
        if (typeof value !== "string") return value.error;
        const parsedValue = Number(value);
        if (!Number.isInteger(parsedValue)) return `Invalid value for --max-context-chars: ${value}`;
        config.maxContextChars = parsedValue;
        break;
      }
      case "--allow-tools": {
        const value = readFlagValue("--allow-tools", ++i);
        if (typeof value !== "string") return value.error;
        config.allowTools = value.split(",").filter(Boolean);
        break;
      }
      case "--deny-tools": {
        const value = readFlagValue("--deny-tools", ++i);
        if (typeof value !== "string") return value.error;
        config.denyTools = value.split(",").filter(Boolean);
        break;
      }
      case "--protected-files": {
        const value = readFlagValue("--protected-files", ++i);
        if (typeof value !== "string") return value.error;
        config.protectedFiles = value.split(",").filter(Boolean);
        break;
      }
      case "--secret-patterns": {
        const value = readFlagValue("--secret-patterns", ++i);
        if (typeof value !== "string") return value.error;
        config.secretPatterns = value.split(",").filter(Boolean);
        break;
      }
      case "--audit-log": {
        const value = readFlagValue("--audit-log", ++i);
        if (typeof value !== "string") return value.error;
        config.auditLog = value;
        break;
      }
      case "--sandbox-vm":
        config.sandboxVm = true;
        break;
      case "--input-files": {
        const value = readFlagValue("--input-files", ++i);
        if (typeof value !== "string") return value.error;
        config.inputFiles = value.split(",").filter(Boolean);
        break;
      }
      case "--output-file": {
        const value = readFlagValue("--output-file", ++i);
        if (typeof value !== "string") return value.error;
        config.outputFile = value;
        break;
      }
      case "--input-format": {
        const value = readFlagValue("--input-format", ++i);
        if (typeof value !== "string") return value.error;
        if (value !== "json" && value !== "text") return `Invalid value for --input-format: ${value} (must be json or text)`;
        config.inputFormat = value;
        break;
      }
      case "--output-format": {
        const value = readFlagValue("--output-format", ++i);
        if (typeof value !== "string") return value.error;
        if (value !== "json" && value !== "text") return `Invalid value for --output-format: ${value} (must be json or text)`;
        config.outputFormat = value;
        break;
      }
      case "--exit-gate": {
        // Repeatable: each occurrence appends one shell command. The
        // exit-gate decorator runs them all on `message_user`; any non-zero
        // exit denies the call so the LLM gets another turn to fix things.
        const value = readFlagValue("--exit-gate", ++i);
        if (typeof value !== "string") return value.error;
        if (!config.exitGates) config.exitGates = [];
        config.exitGates.push(value);
        break;
      }
      case "--file": {
        const nextPath = readFlagValue("--file", ++i);
        if (typeof nextPath !== "string") return nextPath.error;
        const modeErr = setMode("--file", { type: "file", path: nextPath });
        if (modeErr) return modeErr;
        break;
      }
      case "--interactive": {
        const modeErr = setMode("--interactive", { type: "interactive" });
        if (modeErr) return modeErr;
        break;
      }
      case "--protocol": {
        const modeErr = setMode("--protocol", { type: "protocol" });
        if (modeErr) return modeErr;
        break;
      }
    }
  }

  return { config, configFile, requestedMode, resumeSessionId };
}

export function resolveConfig(overrides: Partial<AgentConfig>): AgentConfig {
  const base = defaultConfig();
  return {
    model: overrides.model ?? base.model,
    systemPrompt: overrides.systemPrompt ?? base.systemPrompt,
    rolePrompt: overrides.rolePrompt ?? base.rolePrompt,
    tools: overrides.tools ?? base.tools,
    workDir: overrides.workDir ?? base.workDir,
    verbose: overrides.verbose ?? base.verbose,
    maxIterations: overrides.maxIterations ?? base.maxIterations,
    temperature: overrides.temperature ?? base.temperature,
    instructions: overrides.instructions ?? base.instructions,
    skillsDir: overrides.skillsDir ?? base.skillsDir,
    historyDir: overrides.historyDir ?? base.historyDir,
    commandsDir: overrides.commandsDir ?? base.commandsDir,
    maxContextChars: overrides.maxContextChars ?? base.maxContextChars,
    allowTools: overrides.allowTools && overrides.allowTools.length > 0 ? overrides.allowTools : base.allowTools,
    denyTools: overrides.denyTools && overrides.denyTools.length > 0 ? overrides.denyTools : base.denyTools,
    protectedFiles: overrides.protectedFiles && overrides.protectedFiles.length > 0 ? overrides.protectedFiles : base.protectedFiles,
    secretPatterns: overrides.secretPatterns && overrides.secretPatterns.length > 0 ? overrides.secretPatterns : base.secretPatterns,
    auditLog: overrides.auditLog ?? base.auditLog,
    sandboxVm: overrides.sandboxVm || base.sandboxVm,
    inputFiles: overrides.inputFiles && overrides.inputFiles.length > 0 ? overrides.inputFiles : base.inputFiles,
    outputFile: overrides.outputFile ?? base.outputFile,
    inputFormat: overrides.inputFormat ?? base.inputFormat,
    outputFormat: overrides.outputFormat ?? base.outputFormat,
    currentPhase: overrides.currentPhase ?? base.currentPhase,
    exitGates: overrides.exitGates && overrides.exitGates.length > 0 ? overrides.exitGates : base.exitGates,
  };
}

function isToolName(value: string): value is ToolName {
  return TOOL_NAMES.includes(value as ToolName);
}

function parseToolNames(rawTools: string): string | ToolName[] {
  const requestedNames = rawTools
    .split(",")
    .map((name) => name.trim())
    .filter((name) => name.length > 0);

  const unknownNames = requestedNames.filter((name) => !isToolName(name));
  if (unknownNames.length > 0) {
    return `Unknown tool name(s): ${unknownNames.join(", ")}`;
  }

  return requestedNames as ToolName[];
}
