// Scaffolding: Conversation types, ChatProvider, message construction. Attendees do not edit this file.

// ---------------------------------------------------------------------------
// Conversation types and helpers (scaffolding)
// ---------------------------------------------------------------------------

import type { RawToolCall } from "./tools.js";

export type Message =
  | { role: "system"; content: string }
  | { role: "user"; content: string }
  | { role: "assistant"; content: string };

export type ConversationTurn = { role: "user" | "assistant"; content: string };
export type Conversation = { system: string; turns: ConversationTurn[] };

/**
 * Abstraction over the LLM completion call. Takes the current message
 * history and returns the assistant's response text. The real implementation
 * wraps the OpenAI SDK; tests supply a mock that returns canned responses.
 */
export type ChatProvider = (
  messages: Message[]
) => Promise<string>;

/** Valid calls and parse errors can coexist. The loop feeds errors back to the model only when no valid call is executable. */
export type ParseResult = {
  calls: RawToolCall[];
  errors: string[];
};

export function createConversation(systemPrompt: string): Conversation {
  return { system: systemPrompt, turns: [] };
}

export function conversationToMessages(conversation: Conversation): Message[] {
  return [
    { role: "system", content: conversation.system },
    ...conversation.turns,
  ];
}

export function addTurn(conversation: Conversation, role: "user" | "assistant", content: string): void {
  conversation.turns.push({ role, content });
}

export function isConversationTurn(value: unknown): value is ConversationTurn {
  return typeof value === "object"
    && value !== null
    && (value as Record<string, unknown>).content !== undefined
    && ((value as Record<string, unknown>).role === "user"
      || (value as Record<string, unknown>).role === "assistant")
    && typeof (value as Record<string, unknown>).content === "string";
}
