// Scaffolding: code-decorator types (AgentState, ToolDecorator, allow/deny, snapshotAgentState). Attendees do not edit this file.

// Code-decorator types. A ToolDecorator is a value, not a config file —
// each consumer (agent core or an external workflow) assembles a list
// of decorators and passes them into runPhase / handleTurn.
//
// Decorators run inside the tool-execution loop:
//   before? — inspect/transform an outgoing ToolInvocation; may Allow (with
//             optionally-modified invocation) or Deny (reason → tool result
//             → fed back to the LLM on the next turn).
//   after?  — inspect a returned ToolResult; same Allow/Deny outcome (Deny
//             replaces the tool result with the deny reason).
//
// AgentState is an immutable snapshot the loop hands to each decorator.

import type { AgentConfig } from "./config.js";
import type { Conversation } from "./conversation.js";
import type { ToolResult } from "./tools.js";

export type ToolInvocation = {
  readonly name: string;
  readonly arguments: Readonly<Record<string, unknown>>;
};

export type AgentState = {
  /** Conversation up to (but not including) the current tool result. */
  readonly conversation: Readonly<Conversation>;
  /** Names of tools the agent has access to this turn. */
  readonly enabledTools: ReadonlyArray<string>;
  /** Rough token usage so far (chars/4 approximation; provider-reported once that lands). */
  readonly tokensUsed: number;
  /** Resolved agent config — read-only view. */
  readonly config: Readonly<AgentConfig>;
  /** Current phase name (basename of role-prompt), or null when there is none. */
  readonly currentPhase: string | null;
  /** Agent's working directory (where relative paths in tool args resolve). */
  readonly workDir: string;
};

export type DecoratorOutcome =
  | { readonly kind: "allow"; readonly invocation: ToolInvocation }
  | { readonly kind: "deny"; readonly reason: string };

export type ToolDecorator = {
  readonly name: string;
  /** Sync pre-filter: false skips this decorator without invoking before/after. */
  readonly appliesTo: (invocation: ToolInvocation, state: AgentState) => boolean;
  /** Pre-execution hook. Optional. */
  readonly before?: (
    invocation: ToolInvocation,
    state: AgentState,
  ) => Promise<DecoratorOutcome>;
  /** Post-execution hook. Optional. Sees the tool result and may deny it. */
  readonly after?: (
    invocation: ToolInvocation,
    result: ToolResult,
    state: AgentState,
  ) => Promise<DecoratorOutcome>;
};

/** Constructor: Allow with the (possibly-rewritten) invocation. */
export function allow(invocation: ToolInvocation): DecoratorOutcome {
  return { kind: "allow", invocation };
}

/** Constructor: Deny with reason — short-circuits remaining decorators in the chain. */
export function deny(reason: string): DecoratorOutcome {
  return { kind: "deny", reason };
}

/**
 * Build an AgentState snapshot from the loop's current values. The returned
 * object is shaped as Readonly via the type; callers must not mutate it.
 * `tokensUsed` is a char/4 approximation derived from the conversation.
 */
export function snapshotAgentState(args: {
  conversation: Conversation;
  enabledTools: ReadonlyArray<string>;
  config: AgentConfig;
  currentPhase: string | null;
  workDir: string;
}): AgentState {
  const charCount =
    args.conversation.system.length +
    args.conversation.turns.reduce((acc, t) => acc + t.content.length, 0);
  return {
    conversation: args.conversation,
    enabledTools: args.enabledTools,
    tokensUsed: Math.ceil(charCount / 4),
    config: args.config,
    currentPhase: args.currentPhase,
    workDir: args.workDir,
  };
}
