// Scaffolding: in-process library entry point (runPhase, RunPhaseOptions). Attendees do not edit this file.

// In-process library entry point. The CLI in main.ts/agent.ts wraps these for
// terminal use; workflow tools import runPhase() directly to drive
// the agent loop with their own orchestration. No CLI parsing, no stdin/stdout
// protocol, no interactive mode — just "run one phase to completion."
import OpenAI from "openai";
import * as fs from "fs";
import * as path from "path";
import { tools } from "./agent.js";
import { buildSystemPrompt, handleTurn } from "./exercises.js";
import { resolveConfig, type AgentConfig } from "./config.js";
import { createConversation, type ChatProvider, type Message } from "./conversation.js";
import { getEnabledTools, type ToolName } from "./tools.js";
import type { ToolDecorator } from "./decorators.js";

export type RunPhaseOptions = {
  config: Partial<AgentConfig>;
  userMessage: string;
  apiKey?: string;
  baseUrl?: string;
  /** Code decorators applied in the tool-execution loop. Empty list = no-op. */
  decorators?: ToolDecorator[];
  /**
   * Phase name handed to every decorator's `appliesTo` via
   * `AgentState.currentPhase`. Set this to the phase id (e.g. "discovery",
   * "implementation", "verification") whenever you have it — basename-of-rolePrompt is an
   * unreliable fallback when callers materialize prompts to temp files
   * like `<phase>.prompt.md` or `phase-role-<pid>-<ns>.md`.
   */
  phase?: string;
};

export type PhaseResult = {
  content: string;
  toolCalls: ToolName[];
};

export async function runPhase(opts: RunPhaseOptions): Promise<PhaseResult> {
  const apiKey = opts.apiKey ?? process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    throw new Error("OPENROUTER_API_KEY not set");
  }
  const baseURL = opts.baseUrl ?? "https://openrouter.ai/api/v1";
  const client = new OpenAI({ apiKey, baseURL });

  const config = resolveConfig(opts.config);
  if (opts.phase !== undefined) config.currentPhase = opts.phase;
  const enabledTools = getEnabledTools(config, tools);


  const provider: ChatProvider = async (messages: Message[]) => {
    const response = await client.chat.completions.create({
      model: config.model,
      messages: messages as OpenAI.Chat.ChatCompletionMessageParam[],
      temperature: config.temperature,
      max_tokens: 4096,
    });
    return response.choices[0]?.message?.content ?? "";
  };

  const conversation = createConversation(buildSystemPrompt(config, enabledTools, false));

  // Augment user content with --input-files (mirrors agent.ts processMessage).
  let augmented = opts.userMessage;
  if (config.inputFiles.length > 0) {
    const sections: string[] = [];
    for (const filePat of config.inputFiles) {
      const resolved = path.isAbsolute(filePat) ? filePat : path.resolve(config.workDir, filePat);
      const dir = path.dirname(resolved);
      const base = path.basename(resolved);
      let files: string[];
      if (base.includes("*")) {
        if (!fs.existsSync(dir)) {
          files = [];
        } else {
          const escaped = base.replace(/[.+?^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*");
          const pat = new RegExp("^" + escaped + "$");
          files = fs.readdirSync(dir).filter((f) => pat.test(f)).sort().map((f) => path.join(dir, f));
        }
      } else {
        files = [resolved];
      }
      for (const f of files) {
        if (fs.existsSync(f) && fs.statSync(f).isFile()) {
          sections.push(`--- ${path.basename(f)} ---\n${fs.readFileSync(f, "utf-8")}`);
        }
      }
    }
    if (sections.length > 0) {
      augmented = sections.join("\n\n") + "\n\n" + opts.userMessage;
    }
  }

  const result = await handleTurn(provider, conversation, augmented, config, enabledTools, undefined, opts.decorators ?? []);

  if (config.outputFile) {
    const outDir = path.dirname(config.outputFile);
    if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(config.outputFile, result.content + "\n");
  }

  return { content: result.content, toolCalls: result.toolCalls };
}

export { tools };
export type { AgentConfig, ToolName };
export type {
  ToolDecorator,
  AgentState,
  ToolInvocation,
  DecoratorOutcome,
} from "./decorators.js";
export { allow, deny, snapshotAgentState } from "./decorators.js";

// Re-exports useful for downstream tests that need to construct a
// realistic AgentState snapshot for decorator unit tests.
export { defaultConfig } from "./config.js";
export { createConversation, addTurn } from "./conversation.js";
