// Scaffolding: entry point shim. Attendees do not edit this file.

import { main } from "./agent.js";

const isDirectRun =
  process.argv[1] && import.meta.url === `file://${process.argv[1]}`;
if (isDirectRun) {
  main().then(
    () => process.exit(0),
    (e) => {
      process.stderr.write(`Fatal: ${e}\n`);
      process.exit(1);
    },
  );
}
