// Scaffolding: session save/load + low-level frontmatter/file helpers. Attendees do not edit this file.

import path from "path";
import fs from "fs";
import type { ConversationTurn } from "./conversation.js";
import { isConversationTurn } from "./conversation.js";

export function readTextFileIfExists(filePath: string): string | null {
  const resolvedPath = path.resolve(filePath);
  try {
    return fs.readFileSync(resolvedPath, "utf-8");
  } catch {
    return null;
  }
}

export function parseFrontmatter(content: string): { attributes: Record<string, string>; body: string } {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!match) {
    return { attributes: {}, body: content };
  }

  const attributes: Record<string, string> = {};
  for (const line of match[1].split(/\r?\n/)) {
    const separator = line.indexOf(": ");
    if (separator === -1) {
      continue;
    }

    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 2).trim();
    if (
      (value.startsWith('"') && value.endsWith('"'))
      || (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    attributes[key] = value;
  }

  const body = content.slice(match[0].length);
  const firstBlankLine = body.match(/^[ \t]*\r?\n/);

  return {
    attributes,
    body: firstBlankLine ? body.slice(firstBlankLine[0].length) : body,
  };
}

type SavedSession = {
  timestamp: string;
  workDir: string;
  model: string;
  systemPrompt: string;
  turns: ConversationTurn[];
};

export function sessionFilePath(historyDir: string, sessionId: string): string {
  return path.resolve(historyDir, `${sessionId}.json`);
}

export function truncateSummaryText(text: string, maxChars = 80): string {
  const singleLine = text.replace(/\s+/g, " ").trim();
  if (singleLine.length <= maxChars) {
    return singleLine;
  }
  return `${singleLine.slice(0, maxChars - 3)}...`;
}

export function loadSavedSessionFile(filePath: string): SavedSession | null {
  let raw: string;
  try {
    raw = fs.readFileSync(path.resolve(filePath), "utf-8");
  } catch {
    return null;
  }

  try {
    const parsed = JSON.parse(raw) as unknown;
    if (typeof parsed !== "object" || parsed === null) {
      return null;
    }

    const record = parsed as Record<string, unknown>;
    if (
      typeof record.timestamp !== "string"
      || typeof record.workDir !== "string"
      || typeof record.model !== "string"
      || typeof record.systemPrompt !== "string"
      || !Array.isArray(record.turns)
      || !record.turns.every(isConversationTurn)
    ) {
      return null;
    }

    return {
      timestamp: record.timestamp,
      workDir: record.workDir,
      model: record.model,
      systemPrompt: record.systemPrompt,
      turns: record.turns,
    };
  } catch {
    return null;
  }
}
