// Scaffolding: terminal display + RecordingTerminal. Attendees do not edit this file.

// ---------------------------------------------------------------------------
// TerminalOutput interface
// ---------------------------------------------------------------------------

import type { ToolName, ToolResult, ValidatedToolCall } from "./tools.js";

// Presentation-only boundary for interactive mode. Implementations must not mutate
// agent state. spinnerStart/spinnerStop are expected to be balanced lifecycle calls.
export interface TerminalOutput {
  banner(model: string, tools: ToolName[]): void;
  promptString(): string;
  thinking(text: string): void;
  toolCall(call: ValidatedToolCall): void;
  toolResult(result: ToolResult): void;
  answer(text: string): void;
  error(text: string): void;
  spinnerStart(): void;
  spinnerStop(): void;
  goodbye(): void;
}

// ---------------------------------------------------------------------------
// TerminalEvent / RecordingTerminal (test helper)
// ---------------------------------------------------------------------------

// Captures semantic UI events for test assertions — not exact ANSI bytes or terminal output.
export type TerminalEvent =
  | { type: "banner"; model: string; tools: ToolName[] }
  | { type: "thinking"; text: string }
  | { type: "toolCall"; call: ValidatedToolCall }
  | { type: "toolResult"; result: ToolResult }
  | { type: "answer"; text: string }
  | { type: "error"; text: string }
  | { type: "spinnerStart" }
  | { type: "spinnerStop" }
  | { type: "goodbye" };

// Deterministic test double that stores copied event data for assertions, not a renderer.
export class RecordingTerminal implements TerminalOutput {
  readonly events: TerminalEvent[] = [];

  banner(model: string, tools: ToolName[]): void {
    this.events.push({ type: "banner", model, tools: [...tools] });
  }

  promptString(): string {
    return "> ";
  }

  thinking(text: string): void {
    this.events.push({ type: "thinking", text });
  }

  toolCall(call: ValidatedToolCall): void {
    this.events.push({ type: "toolCall", call: { ...call, arguments: { ...call.arguments } } });
  }

  toolResult(result: ToolResult): void {
    this.events.push({ type: "toolResult", result: result.ok ? { ok: true, output: result.output } : { ok: false, error: result.error } });
  }

  answer(text: string): void {
    this.events.push({ type: "answer", text });
  }

  error(text: string): void {
    this.events.push({ type: "error", text });
  }

  spinnerStart(): void {
    this.events.push({ type: "spinnerStart" });
  }

  spinnerStop(): void {
    this.events.push({ type: "spinnerStop" });
  }

  goodbye(): void {
    this.events.push({ type: "goodbye" });
  }
}

// ---------------------------------------------------------------------------
// Tool call formatting (pure, testable)
// ---------------------------------------------------------------------------

/** Format a single tool-call argument value for human display (YAML-ish style).
 *  - Strings: unquoted. Multiline strings use YAML block-scalar (`|`) form.
 *  - Numbers/booleans: literal representation.
 *  - Objects/arrays: compact JSON.
 */
const MAX_ARG_LINES = 8;

export function formatArgValue(value: unknown): string {
  if (typeof value === "string") {
    if (value.includes("\n")) {
      const lines = value.split("\n");
      if (lines.length > MAX_ARG_LINES) {
        const shown = lines.slice(0, MAX_ARG_LINES).map((l) => `      ${l}`).join("\n");
        return `|\n${shown}\n      [+${lines.length - MAX_ARG_LINES} more lines]`;
      }
      return "|\n" + lines.map((l) => `      ${l}`).join("\n");
    }
    return value;
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  return JSON.stringify(value);
}

// ---------------------------------------------------------------------------
// Real Terminal implementation
// ---------------------------------------------------------------------------

const NO_COLOR = process.env.NO_COLOR !== undefined;

const RESET = NO_COLOR ? "" : "\x1b[0m";
const BOLD = NO_COLOR ? "" : "\x1b[1m";
const DIM = NO_COLOR ? "" : "\x1b[2m";
const CYAN = NO_COLOR ? "" : "\x1b[36m";
const YELLOW = NO_COLOR ? "" : "\x1b[33m";
const GREEN = NO_COLOR ? "" : "\x1b[32m";
const RED = NO_COLOR ? "" : "\x1b[31m";
const WHITE = NO_COLOR ? "" : "\x1b[37m";
const GRAY = NO_COLOR ? "" : "\x1b[90m";

const SPINNER_FRAMES = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];
// Truncates only the human-facing terminal display — does NOT change the tool result
// flowing back into the agent loop.
const MAX_RESULT_LINES = 10;

// Interactive-only renderer: human output to stdout, spinner frames to stderr (to avoid
// corrupting protocol output). NO_COLOR env var disables ANSI styling.
export class Terminal implements TerminalOutput {
  private spinnerTimer: ReturnType<typeof setInterval> | null = null;
  private spinnerFrame = 0;

  banner(model: string, tools: ToolName[]): void {
    const toolList = tools.join(", ");
    const width = Math.max(model.length + 10, toolList.length + 10, 50);
    const pad = (s: string) => s.padEnd(width - 4);

    console.log(`${DIM}╭${"─".repeat(width - 2)}╮${RESET}`);
    console.log(`${DIM}│${RESET} ${pad(`model: ${model}`)} ${DIM}│${RESET}`);
    console.log(`${DIM}│${RESET} ${pad(`tools: ${toolList}`)} ${DIM}│${RESET}`);
    console.log(`${DIM}╰${"─".repeat(width - 2)}╯${RESET}`);
    console.log();
  }

  promptString(): string {
    return `${CYAN}${BOLD}> ${RESET}`;
  }

  thinking(text: string): void {
    const cleaned = text.replace(/^THINKING:\s*/i, "").trim();
    if (!cleaned) return;
    for (const line of cleaned.split("\n")) {
      console.log(`  ${GRAY}● ${line}${RESET}`);
    }
  }

  toolCall(call: ValidatedToolCall): void {
    console.log(`  ${CYAN}${BOLD}CALLING:${RESET} ${YELLOW}${BOLD}${call.name}${RESET}`);
    for (const [key, value] of Object.entries(call.arguments)) {
      console.log(`    ${key}: ${formatArgValue(value)}`);
    }
  }

  toolResult(result: ToolResult): void {
    const isError = !result.ok;
    const text = result.ok ? result.output : result.error;
    const prefix = isError
      ? `  ${RED}✗${RESET} `
      : `  ${GREEN}${DIM}✓${RESET} `;

    const lines = text.split("\n");
    if (lines.length <= MAX_RESULT_LINES) {
      for (const [i, line] of lines.entries()) {
        console.log(`${i === 0 ? prefix : "    "}${isError ? RED : `${GREEN}${DIM}`}${line}${RESET}`);
      }
    } else {
      for (let i = 0; i < MAX_RESULT_LINES; i++) {
        console.log(`${i === 0 ? prefix : "    "}${isError ? RED : `${GREEN}${DIM}`}${lines[i]}${RESET}`);
      }
      const remaining = lines.length - MAX_RESULT_LINES;
      console.log(`    ${GRAY}[+${remaining} more lines]${RESET}`);
    }
  }

  answer(text: string): void {
    console.log(`  ${WHITE}${BOLD}■${RESET} ${text.split("\n").join("\n    ")}`);
  }

  error(text: string): void {
    console.log(`  ${RED}${BOLD}✗ ${text}${RESET}`);
  }

  spinnerStart(): void {
    this.spinnerFrame = 0;
    this.spinnerTimer = setInterval(() => {
      process.stderr.write(
        `\r  ${GRAY}${SPINNER_FRAMES[this.spinnerFrame % SPINNER_FRAMES.length]}${RESET}`
      );
      this.spinnerFrame++;
    }, 80);
  }

  spinnerStop(): void {
    if (this.spinnerTimer) {
      clearInterval(this.spinnerTimer);
      this.spinnerTimer = null;
      process.stderr.write("\r  \r");
    }
  }

  goodbye(): void {
    console.log(`${GRAY}goodbye.${RESET}`);
  }
}
