// Scaffolding: tool schemas + non-exercise tool implementations (write_file, message_user, ask_user, read_board, update_board). Exercise tools live in exercises.ts. Attendees do not edit this file.

import fs from "fs";
import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";

export const TOOL_NAMES = ["read_file", "write_file", "edit_file", "shell", "list_files", "web_fetch", "message_user", "ask_user", "read_board", "update_board"] as const;
export type ToolName = typeof TOOL_NAMES[number];

export type ToolResult =
  | { ok: true; output: string }
  | { ok: false; error: string };

export type ToolSelection =
  | { type: "all" }
  | { type: "only"; tools: ToolName[] };

export type SkillInfo = {
  name: string;
  description: string;
  path: string;
};

export type CommandPrompt = {
  name: string;
  description: string;
  argumentHint: string | null;
  path: string;
};

export type ContextUsage = {
  system: number;
  conversation: number;
  tools: number;
  total: number;
  limit: number | null;
  percentage: number | null;
};

/**
 * A tool the agent can invoke. The `schema` is a Zod type used both for
 * validation (in `execute`) and for JSON Schema generation (in the system prompt).
 * The `execute` function receives raw JSON arguments, validates them against
 * the schema, performs the side effect, and returns a string result.
 * Errors are returned as strings prefixed with "Error:", never thrown.
 */
export type Tool = {
  name: ToolName;
  description: string;
  schema: z.ZodType;
  execute: (args: Record<string, unknown>) => ToolResult | Promise<ToolResult>;
};

export type RawToolCall = { name: string; arguments: Record<string, unknown> };
export type ValidatedToolCall = { name: ToolName; arguments: Record<string, unknown> };

export type PermissionResult = { allowed: boolean; reason: string };
export type AuditEvent = {
  timestamp: string;
  event: "tool_call" | "tool_result" | "permission_denied" | "sandbox_violation" | "secret_redacted" | "checkpoint_created" | "checkpoint_restored" | "decorator_applied";
  details: Record<string, unknown>;
};
export type CheckpointInfo = { id: string; timestamp: string; path: string };

export const ReadFileParams = z.object({
  path: z.string().describe("The file path to read"),
});

export const WriteFileParams = z.object({
  path: z.string().describe("The file path to write to"),
  content: z.string().describe("The content to write"),
});

export const EditFileParams = z.object({
  path: z.string().describe("The file path to edit"),
  line_start: z.number().int().describe("Start line of the range to edit (1-indexed)"),
  line_end: z.number().int().describe("End line of the range to edit (1-indexed, inclusive)"),
  old_text: z.string().describe("The text to find within the line range"),
  new_text: z.string().describe("The replacement text"),
});

export const ShellParams = z.object({
  command: z.string().describe("The shell command to execute"),
});

export const ListFilesParams = z.object({
  path: z.string().describe("Directory path to list"),
  max_depth: z.number().int().describe("Maximum depth to recurse (1 = immediate children only)"),
});

export const WebFetchParams = z.object({
  url: z.string().describe("The URL to fetch"),
});

export const MessageUserParams = z.object({
  message: z.string().describe("The final response to deliver to the user"),
});

export function executeWriteFile(args: Record<string, unknown>): ToolResult {
  try {
    const { path: filePath, content } = WriteFileParams.parse(args);
    fs.writeFileSync(filePath, content, "utf-8");
    return { ok: true, output: `Successfully wrote to ${filePath}` };
  } catch (e) {
    if (e instanceof z.ZodError) {
      return { ok: false, error: `invalid arguments: ${e.message}` };
    }
    return { ok: false, error: `writing file: ${e}` };
  }
}

export function executeMessageUser(args: Record<string, unknown>): ToolResult {
  try {
    const { message } = MessageUserParams.parse(args);
    return { ok: true, output: message };
  } catch (e) {
    return { ok: false, error: `invalid arguments: ${e}` };
  }
}

// Workflow scaffolding: ask_user tool (same as message_user, different semantic signal)
export const AskUserParams = z.object({
  question: z.string().describe("The question to ask the user"),
});

export function executeAskUser(args: Record<string, unknown>): ToolResult {
  try {
    const { question } = AskUserParams.parse(args);
    return { ok: true, output: question };
  } catch (e) {
    return { ok: false, error: `invalid arguments: ${e}` };
  }
}

// Workflow scaffolding: read_board tool
export const ReadBoardParams = z.object({
  path: z.string().describe("Path to the board.json file"),
});

export function executeReadBoard(args: Record<string, unknown>): ToolResult {
  try {
    const { path: boardPath } = ReadBoardParams.parse(args);
    if (!fs.existsSync(boardPath)) {
      return { ok: false, error: `board not found: ${boardPath}` };
    }
    const content = fs.readFileSync(boardPath, "utf-8");
    JSON.parse(content);
    return { ok: true, output: content };
  } catch (e) {
    if (e instanceof z.ZodError) return { ok: false, error: `invalid arguments: ${e.message}` };
    return { ok: false, error: `reading board: ${e}` };
  }
}

// Workflow scaffolding: update_board tool.
export const UpdateBoardParams = z.object({
  path: z.string().describe("Path to the board.json file"),
  phase: z.string().describe("Existing workflow phase to update"),
  status: z.string().describe("New workflow-defined status"),
  artifact: z.string().nullable().optional().describe("Optional path to the artifact produced by this phase"),
});

export function executeUpdateBoard(args: Record<string, unknown>): ToolResult {
  try {
    const parsed = UpdateBoardParams.parse(args);
    const { path: boardPath, phase, status, artifact } = parsed;
    if (!fs.existsSync(boardPath)) {
      return { ok: false, error: `board not found: ${boardPath}` };
    }
    const board = JSON.parse(fs.readFileSync(boardPath, "utf-8"));
    if (!board.phases || !(phase in board.phases)) {
      return { ok: false, error: `unknown phase: ${phase}` };
    }
    board.phases[phase].status = status;
    if (artifact !== undefined && artifact !== null) board.phases[phase].artifact = artifact;
    board.currentPhase = phase;
    fs.writeFileSync(boardPath, JSON.stringify(board, null, 2) + "\n");
    return { ok: true, output: JSON.stringify(board, null, 2) };
  } catch (e) {
    if (e instanceof z.ZodError) return { ok: false, error: `invalid arguments: ${e.message}` };
    return { ok: false, error: `updating board: ${e}` };
  }
}

export function formatToolForPrompt(tool: Tool): string {
  const schema = zodToJsonSchema(tool.schema, { target: "openApi3" });
  return [
    `### ${tool.name}`,
    tool.description,
    "Parameters:",
    "```json",
    JSON.stringify(schema, null, 2),
    "```",
  ].join("\n");
}

type AgentConfig = {
  tools: ToolSelection;
};

// Empty config.tools means "all tools." message_user is always force-retained
// so the agent loop can terminate cleanly.
export function getEnabledTools(config: AgentConfig, allTools: Tool[]): Tool[] {
  const selectedTools = config.tools;
  if (selectedTools.type === "all") return allTools;
  return allTools.filter((t) => selectedTools.tools.includes(t.name) || t.name === "message_user");
}
