// Scaffolding: CLI, REPL, tool registry, main entry point. Attendees do not edit this file.

use crate::config::{parse_cli_config, resolve_config, AgentConfig, RequestedMode};
use crate::conversation::{
    build_message, message_role_and_content, ChatCompletionRequestMessage,
    ChatCompletionRequestUserMessageArgs, ChatProvider, Conversation,
    CreateChatCompletionRequestArgs,
};
use crate::decorators::ToolDecorator;
use crate::exercises::exit_gate;
use crate::exercises::{
    apply_compaction, build_system_prompt, discover_commands, discover_skills, execute_command,
    execute_edit_file, execute_list_files, execute_read_file, execute_shell_default,
    execute_web_fetch, extract_memories, format_conversation_for_compaction, handle_turn,
    load_instructions, load_memories, load_past_session_summaries, load_session, measure_context,
    save_session, should_auto_compact,
};
use crate::terminal::{Terminal, TerminalOutput};
use crate::tools::{
    execute_ask_user, execute_message_user, execute_read_board, execute_update_board,
    execute_write_file, get_enabled_tools, AskUserParams, EditFileParams, ListFilesParams,
    MessageUserParams, ReadBoardParams, ReadFileParams, ShellParams, Tool, ToolName, ToolResult,
    UpdateBoardParams, WebFetchParams, WriteFileParams,
};
use anyhow::{bail, Result};
use async_openai::{config::OpenAIConfig, Client};
use regex::Regex;
use rustyline::{error::ReadlineError, DefaultEditor};
use schemars::schema_for;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::env;
use std::fs;
use std::io::{self, BufRead, ErrorKind, Write};
use std::path::{Path, PathBuf};
use std::sync::LazyLock;

/// Build the decorator list for a given config: empty when `exit_gates` is
/// empty, otherwise a single `exit-gate` decorator that gates `message_user`
/// on the configured shell commands. Called at each handle_turn invocation.
fn exit_gate_decorators(config: &AgentConfig) -> Vec<ToolDecorator> {
    if config.exit_gates.is_empty() {
        Vec::new()
    } else {
        vec![exit_gate(config.exit_gates.clone())]
    }
}

static FILE_PROMPT_SPLIT_REGEX: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?m)^---$").unwrap());
pub(crate) fn parse_file_prompts(content: &str) -> Vec<String> {
    FILE_PROMPT_SPLIT_REGEX
        .split(content)
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect()
}

fn prepend_input_files(user_content: &str, config: &AgentConfig) -> String {
    if config.input_files.is_empty() {
        return user_content.to_string();
    }

    fn glob_matches(pattern: &str, file_name: &str) -> bool {
        let escaped = pattern
            .chars()
            .map(|ch| {
                if ch == '*' {
                    ".*".to_string()
                } else {
                    regex::escape(&ch.to_string())
                }
            })
            .collect::<String>();
        Regex::new(&format!("^{escaped}$"))
            .map(|re| re.is_match(file_name))
            .unwrap_or(false)
    }

    let mut sections = Vec::new();
    for file_pat in &config.input_files {
        let resolved = if file_pat.is_absolute() {
            file_pat.clone()
        } else {
            config.work_dir.join(file_pat)
        };

        let dir = resolved
            .parent()
            .map(Path::to_path_buf)
            .unwrap_or_else(|| PathBuf::from("."));
        let base = resolved
            .file_name()
            .map(|name| name.to_string_lossy().into_owned())
            .unwrap_or_default();

        let files = if base.contains('*') {
            if !dir.is_dir() {
                Vec::new()
            } else {
                let mut expanded = fs::read_dir(&dir)
                    .ok()
                    .into_iter()
                    .flatten()
                    .filter_map(|entry| entry.ok())
                    .map(|entry| entry.path())
                    .filter(|path| {
                        path.file_name()
                            .map(|name| glob_matches(&base, &name.to_string_lossy()))
                            .unwrap_or(false)
                    })
                    .collect::<Vec<_>>();
                expanded.sort();
                expanded
            }
        } else {
            vec![resolved]
        };

        for file_path in files {
            if file_path.is_file() {
                if let Ok(content) = fs::read_to_string(&file_path) {
                    let file_name = file_path
                        .file_name()
                        .map(|name| name.to_string_lossy().into_owned())
                        .unwrap_or_else(|| file_path.to_string_lossy().into_owned());
                    sections.push(format!("--- {} ---\n{}", file_name, content));
                }
            }
        }
    }

    if sections.is_empty() {
        user_content.to_string()
    } else {
        format!("{}\n\n{}", sections.join("\n\n"), user_content)
    }
}

fn write_output_file(config: &AgentConfig, content: &str) -> Result<()> {
    if let Some(path) = &config.output_file {
        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() {
                fs::create_dir_all(parent)?;
            }
        }
        fs::write(path, format!("{}\n", content))?;
    }
    Ok(())
}

pub(crate) fn is_interactive_eof(error: &ReadlineError) -> bool {
    matches!(error, ReadlineError::Eof)
        || matches!(error, ReadlineError::Io(io_error) if matches!(io_error.kind(), ErrorKind::UnexpectedEof | ErrorKind::BrokenPipe))
}
#[derive(Debug, PartialEq, Eq)]
pub(crate) enum CommandResult {
    Quit,
    Compact { summary: String },
    Custom { response: String },
    Unknown { name: String },
}

pub(crate) fn is_command(input: &str) -> bool {
    input.starts_with('/')
}

fn load_compaction_prompt() -> String {
    // Rust-idiomatic source-relative resolution for shared prompt assets.
    let template_path = if let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") {
        std::path::PathBuf::from(manifest_dir).join("../compaction-prompt.txt")
    } else {
        std::path::PathBuf::from("../compaction-prompt.txt")
    };

    fs::read_to_string(&template_path).expect("Failed to read compaction prompt template")
}

pub(crate) async fn handle_command(
    input: &str,
    provider: &dyn ChatProvider,
    conversation: &Conversation,
    agent_config: &AgentConfig,
    session_id: &str,
) -> Result<CommandResult> {
    let command_name = input
        .trim_start_matches('/')
        .split_whitespace()
        .next()
        .unwrap_or_default();

    match command_name {
        "quit" | "exit" => Ok(CommandResult::Quit),
        "compact" => {
            let compacted = format_conversation_for_compaction(conversation);
            // Module 02 scaffolding: session-aware compaction prompt
            let past_summaries = load_past_session_summaries(
                agent_config.history_dir.as_deref().unwrap_or(Path::new("")),
                session_id,
                provider,
            )
            .await;
            let past_section = if past_summaries.is_empty() {
                String::new()
            } else {
                format!("Previous sessions:\n{}\n\n", past_summaries)
            };
            let prompt = load_compaction_prompt()
                .replace("{{CONVERSATION}}", &compacted)
                .replace("{{PAST_SESSIONS}}", &past_section);

            let prompt_message: ChatCompletionRequestMessage =
                ChatCompletionRequestUserMessageArgs::default()
                    .content(prompt)
                    .build()?
                    .into();

            let summary = provider.complete(&[prompt_message]).await?;
            Ok(CommandResult::Compact { summary })
        }
        other => {
            // Module 02 scaffolding: custom command dispatch
            let commands = discover_commands(agent_config.commands_dir.as_deref());
            if let Some(cmd) = commands.iter().find(|c| c.name == other) {
                let args = input
                    .trim_start_matches('/')
                    .trim()
                    .strip_prefix(other)
                    .unwrap_or("")
                    .trim();
                let prompt = execute_command(cmd, args);
                let msg = ChatCompletionRequestUserMessageArgs::default()
                    .content(prompt)
                    .build()?
                    .into();
                let response = provider.complete(&[msg]).await?;
                Ok(CommandResult::Custom { response })
            } else {
                Ok(CommandResult::Unknown {
                    name: other.to_string(),
                })
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Scaffolding: tool registry, entry point
// ---------------------------------------------------------------------------

// Tool registry: single source of truth for prompt generation and runtime dispatch.
// message_user is a protocol terminator (signals task completion), not a side-effecting tool.
pub(crate) fn tools() -> Vec<Tool> {
    vec![
        Tool {
            name: ToolName::ReadFile,
            description: "Read the entire contents of a file at the given path. This tool does NOT support pagination, line ranges, or partial reads — it always returns the whole file. Do not pass start, end, line_start, line_end, offset, or limit; the only parameter is path.",
            schema: serde_json::to_value(schema_for!(ReadFileParams)).unwrap_or(Value::Null),
            execute: execute_read_file,
        },
        Tool {
            name: ToolName::WriteFile,
            description: "Write content to a file at the given path",
            schema: serde_json::to_value(schema_for!(WriteFileParams)).unwrap_or(Value::Null),
            execute: execute_write_file,
        },
        Tool {
            name: ToolName::EditFile,
            description: "Edit a file by replacing old_text with new_text within the specified line range. The file is unmodified if old_text is not found in the range.",
            schema: serde_json::to_value(schema_for!(EditFileParams)).unwrap_or(Value::Null),
            execute: execute_edit_file,
        },
        Tool {
            name: ToolName::Shell,
            description: "Execute a shell command and return its output",
            schema: serde_json::to_value(schema_for!(ShellParams)).unwrap_or(Value::Null),
            execute: execute_shell_default,
        },
        Tool {
            name: ToolName::ListFiles,
            description: "Recursively list files and directories at the given path up to a maximum depth. Returns paths relative to the given directory.",
            schema: serde_json::to_value(schema_for!(ListFilesParams)).unwrap_or(Value::Null),
            execute: execute_list_files,
        },
        Tool {
            name: ToolName::WebFetch,
            description: "Fetch the contents of a URL and return the response body as text",
            schema: serde_json::to_value(schema_for!(WebFetchParams)).unwrap_or(Value::Null),
            execute: execute_web_fetch,
        },
        Tool {
            name: ToolName::MessageUser,
            description: "Deliver your final response to the user. Use this when the task is complete.",
            schema: serde_json::to_value(schema_for!(MessageUserParams)).unwrap_or(Value::Null),
            execute: execute_message_user,
        },
        Tool {
            name: ToolName::AskUser,
            description: "Ask the user a question and wait for their response. Use at review gates when human input is needed before continuing.",
            schema: serde_json::to_value(schema_for!(AskUserParams)).unwrap_or(Value::Null),
            execute: execute_ask_user,
        },
        Tool {
            name: ToolName::ReadBoard,
            description: "Read the current state of the kanban board. Returns the board JSON showing phase statuses and artifacts.",
            schema: serde_json::to_value(schema_for!(ReadBoardParams)).unwrap_or(Value::Null),
            execute: execute_read_board,
        },
        Tool {
            name: ToolName::UpdateBoard,
            description: "Update a phase on the kanban board. Changes the status and optionally records the artifact path.",
            schema: serde_json::to_value(schema_for!(UpdateBoardParams)).unwrap_or(Value::Null),
            execute: execute_update_board,
        },
    ]
}

/// JSON shape for stdin input lines.
#[derive(Debug, Deserialize)]
pub(crate) struct InputLine {
    pub(crate) content: String,
}

/// JSON shape for stdout output lines.
#[derive(Debug, Serialize)]
pub(crate) struct OutputLine {
    pub(crate) content: String,
    pub(crate) tool_calls: Vec<ToolName>,
}

fn write_protocol_output<W: Write>(
    stdout: &mut W,
    config: &AgentConfig,
    content: &str,
    tool_calls: Vec<ToolName>,
) -> Result<()> {
    if config.output_format == "text" {
        writeln!(stdout, "{}", content)?;
    } else {
        let response = OutputLine {
            content: content.to_string(),
            tool_calls,
        };
        writeln!(stdout, "{}", serde_json::to_string(&response)?)?;
    }
    stdout.flush()?;
    Ok(())
}

struct OpenRouterProvider {
    client: Client<OpenAIConfig>,
    model: String,
    temperature: f32,
}

#[async_trait::async_trait(?Send)]
impl ChatProvider for OpenRouterProvider {
    async fn complete(&self, messages: &[ChatCompletionRequestMessage]) -> Result<String> {
        let request = CreateChatCompletionRequestArgs::default()
            .model(&self.model)
            .messages(messages.to_vec())
            .temperature(self.temperature)
            .max_tokens(4096_u16)
            .build()?;

        let response = self.client.chat().create(request).await?;

        Ok(response
            .choices
            .first()
            .and_then(|choice| choice.message.content.clone())
            .unwrap_or_default())
    }
}

async fn process_non_interactive_message<W: Write>(
    user_content: &str,
    provider: &dyn ChatProvider,
    config: &AgentConfig,
    available_tools: &[Tool],
    conversation: &mut Conversation,
    session_id: &str,
    stdout: &mut W,
) -> Result<bool> {
    if is_command(user_content) {
        match handle_command(user_content, provider, conversation, config, session_id).await? {
            CommandResult::Quit => {
                write_protocol_output(stdout, config, "goodbye.", vec![])?;
                return Ok(false);
            }
            CommandResult::Compact { summary } => {
                let before = conversation.len();
                apply_compaction(conversation, &summary)?;
                let after = conversation.len();
                write_protocol_output(
                    stdout,
                    config,
                    &format!("Compacted {} messages → {} messages", before, after),
                    vec![],
                )?;
                return Ok(true);
            }
            CommandResult::Custom { response } => {
                write_protocol_output(stdout, config, &response, vec![])?;
                return Ok(true);
            }
            CommandResult::Unknown { name } => {
                write_protocol_output(
                    stdout,
                    config,
                    &format!("Unknown command: /{}", name),
                    vec![],
                )?;
                return Ok(true);
            }
        }
    }

    let augmented_user_content = prepend_input_files(user_content, config);

    let result = handle_turn(
        provider,
        config,
        available_tools,
        conversation,
        &augmented_user_content,
        None,
        &exit_gate_decorators(config),
    )
    .await?;

    // Module 02 scaffolding: post-turn context management
    let system_prompt = message_role_and_content(&conversation.system)
        .map(|(_, content)| content)
        .unwrap_or_default();
    let usage = measure_context(
        &system_prompt,
        &conversation.turns,
        available_tools,
        config.max_context_chars,
    );

    if should_auto_compact(&usage) {
        let compact_text = format_conversation_for_compaction(conversation);
        let past_summaries = load_past_session_summaries(
            config.history_dir.as_deref().unwrap_or(Path::new("")),
            session_id,
            provider,
        )
        .await;
        let past_section = if past_summaries.is_empty() {
            String::new()
        } else {
            format!("Previous sessions:\n{}\n\n", past_summaries)
        };
        let compact_prompt = load_compaction_prompt()
            .replace("{{CONVERSATION}}", &compact_text)
            .replace("{{PAST_SESSIONS}}", &past_section);
        let msg: ChatCompletionRequestMessage = ChatCompletionRequestUserMessageArgs::default()
            .content(compact_prompt)
            .build()?
            .into();
        let summary = provider.complete(&[msg]).await?;
        apply_compaction(conversation, &summary)?;
        if config.verbose {
            eprintln!("Auto-compacted conversation (context budget exceeded)");
        }
    }

    if let Some(ref history_dir) = config.history_dir {
        let _ = save_session(history_dir, session_id, &conversation.as_messages());
    }

    let _ = extract_memories(provider, user_content, &result.content, &config.work_dir).await;

    write_protocol_output(stdout, config, &result.content, result.tool_calls)?;
    write_output_file(config, &result.content)?;

    Ok(true)
}

/// Stdin/stdout protocol driver. Reads JSON-lines from stdin, dispatches each
/// to [`handle_turn`], writes one JSON-line response to stdout per input.
/// Falls back to treating input as plain text if JSON parsing fails.
/// Conversation history accumulates across lines (multi-turn).
async fn run_inner() -> Result<()> {
    let args = env::args().skip(1).collect::<Vec<_>>();
    let cli_config = parse_cli_config(&args)?;
    let agent_config = resolve_config(&cli_config);
    // Cross-language note: TS/Scala use UUID; Rust uses timestamp-based ID (no uuid crate)
    if cli_config.resume_session_id.is_some() && agent_config.history_dir.is_none() {
        bail!("--resume requires --history-dir");
    }
    let fresh_session_id = format!(
        "session-{}",
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis()
    );
    let session_id = cli_config
        .resume_session_id
        .clone()
        .unwrap_or(fresh_session_id);

    let runtime_mode = match &cli_config.requested_mode {
        RequestedMode::Auto => {
            if atty::is(atty::Stream::Stdin) {
                RequestedMode::Interactive
            } else {
                RequestedMode::Protocol
            }
        }
        other => other.clone(),
    };
    let interactive_mode = matches!(runtime_mode, RequestedMode::Interactive);

    let api_key = match env::var("OPENROUTER_API_KEY") {
        Ok(key) if !key.is_empty() => key,
        _ => bail!("Set OPENROUTER_API_KEY environment variable"),
    };

    let config = OpenAIConfig::new()
        .with_api_key(api_key)
        .with_api_base("https://openrouter.ai/api/v1");
    let client = Client::with_config(config);

    let provider = OpenRouterProvider {
        client,
        model: agent_config.model.clone(),
        temperature: agent_config.temperature,
    };
    let all_tools = tools();
    let available_tools = get_enabled_tools(&agent_config, &all_tools);

    let resumed_conversation = if cli_config.resume_session_id.is_some() {
        load_session(agent_config.history_dir.as_ref().unwrap(), &session_id)?
    } else {
        None
    };
    if cli_config.resume_session_id.is_some() && resumed_conversation.is_none() {
        bail!("Session not found: {session_id}");
    }
    if agent_config.verbose {
        if let Some(ref resumed) = resumed_conversation {
            eprintln!(
                "Resumed session {} with {} turns",
                session_id,
                resumed.len().saturating_sub(1)
            );
        }
    }
    let mut conversation = Conversation::new(build_system_prompt(
        &agent_config,
        &available_tools,
        interactive_mode,
    ));
    if let Some(messages) = resumed_conversation {
        conversation.turns = messages.into_iter().skip(1).collect();
    }

    // Module 02 scaffolding: context injection
    let mut context_sections = String::new();
    if let Some(instructions) =
        load_instructions(&agent_config.work_dir, agent_config.instructions.as_deref())
    {
        context_sections.push_str("\n\n## Project Instructions\n\n");
        context_sections.push_str(&instructions);
    }
    let skills = discover_skills(agent_config.skills_dir.as_deref());
    if !skills.is_empty() {
        context_sections.push_str("\n\n## Available Skills\n\n");
        for s in &skills {
            context_sections.push_str(&format!("- {}: {}\n", s.name, s.description));
        }
    }
    if let Some(memories) = load_memories(&agent_config.work_dir) {
        context_sections.push_str("\n\n## Things I remember from previous conversations\n\n");
        context_sections.push_str(&memories);
    }
    if !context_sections.is_empty() {
        let existing_system = message_role_and_content(&conversation.system)
            .map(|(_, content)| content)
            .unwrap_or_default();
        conversation.system = build_message("system", &(existing_system + &context_sections))?;
    }

    if interactive_mode {
        let terminal = Terminal::new();
        let tool_names = available_tools
            .iter()
            .map(|tool| tool.name)
            .filter(|name| *name != ToolName::MessageUser)
            .collect::<Vec<_>>();
        terminal.banner(&agent_config.model, &tool_names);

        let mut editor = DefaultEditor::new()?;
        let mut prompt = terminal.prompt_string();
        let mut buffer = String::new();

        loop {
            match editor.readline(&prompt) {
                Ok(line) => {
                    if let Some(continued) = line.strip_suffix('\\') {
                        buffer.push_str(continued);
                        buffer.push('\n');
                        prompt = "  ".to_string();
                        continue;
                    }

                    let full_line = if buffer.is_empty() {
                        line
                    } else {
                        let mut combined = std::mem::take(&mut buffer);
                        combined.push_str(&line);
                        combined
                    };

                    let user_content = full_line.trim().to_string();
                    prompt = terminal.prompt_string();
                    if user_content.is_empty() {
                        continue;
                    }
                    let _ = editor.add_history_entry(&full_line);

                    if is_command(&user_content) {
                        match handle_command(
                            &user_content,
                            &provider,
                            &conversation,
                            &agent_config,
                            &session_id,
                        )
                        .await?
                        {
                            CommandResult::Quit => {
                                terminal.goodbye();
                                break;
                            }
                            CommandResult::Compact { summary } => {
                                let before = conversation.len();
                                apply_compaction(&mut conversation, &summary)?;
                                let after = conversation.len();
                                terminal.tool_result(&ToolResult::Ok(format!(
                                    "Compacted {} messages → {} messages",
                                    before, after
                                )));
                                println!();
                                continue;
                            }
                            CommandResult::Custom { response } => {
                                terminal.answer(&response);
                                println!();
                                continue;
                            }
                            CommandResult::Unknown { name } => {
                                terminal.error(&format!("Unknown command: /{}", name));
                                println!();
                                continue;
                            }
                        }
                    }

                    let augmented_user_content = prepend_input_files(&user_content, &agent_config);

                    let result = handle_turn(
                        &provider,
                        &agent_config,
                        &available_tools,
                        &mut conversation,
                        &augmented_user_content,
                        Some(&terminal),
                        &exit_gate_decorators(&agent_config),
                    )
                    .await?;

                    // Module 02 scaffolding: post-turn context management
                    let system_prompt = message_role_and_content(&conversation.system)
                        .map(|(_, content)| content)
                        .unwrap_or_default();
                    let usage = measure_context(
                        &system_prompt,
                        &conversation.turns,
                        &available_tools,
                        agent_config.max_context_chars,
                    );

                    if should_auto_compact(&usage) {
                        let compact_text = format_conversation_for_compaction(&conversation);
                        let past_summaries = load_past_session_summaries(
                            agent_config.history_dir.as_deref().unwrap_or(Path::new("")),
                            &session_id,
                            &provider,
                        )
                        .await;
                        let past_section = if past_summaries.is_empty() {
                            String::new()
                        } else {
                            format!("Previous sessions:\n{}\n\n", past_summaries)
                        };
                        let compact_prompt = load_compaction_prompt()
                            .replace("{{CONVERSATION}}", &compact_text)
                            .replace("{{PAST_SESSIONS}}", &past_section);
                        let msg: ChatCompletionRequestMessage =
                            ChatCompletionRequestUserMessageArgs::default()
                                .content(compact_prompt)
                                .build()?
                                .into();
                        let summary = provider.complete(&[msg]).await?;
                        apply_compaction(&mut conversation, &summary)?;
                        if agent_config.verbose {
                            eprintln!("Auto-compacted conversation (context budget exceeded)");
                        }
                    }

                    if let Some(ref history_dir) = agent_config.history_dir {
                        let _ = save_session(history_dir, &session_id, &conversation.as_messages());
                    }

                    let _ = extract_memories(
                        &provider,
                        &user_content,
                        &result.content,
                        &agent_config.work_dir,
                    )
                    .await;

                    write_output_file(&agent_config, &result.content)?;

                    println!();
                }
                Err(ReadlineError::Interrupted) => {
                    buffer.clear();
                    prompt = terminal.prompt_string();
                    continue;
                }
                Err(e) if is_interactive_eof(&e) => {
                    terminal.goodbye();
                    break;
                }
                Err(e) => {
                    eprintln!("Error: {e}");
                    break;
                }
            }
        }
    } else {
        let mut stdout = io::stdout().lock();
        if let RequestedMode::File(file_path) = runtime_mode {
            let content = fs::read_to_string(&file_path)?;
            for prompt in parse_file_prompts(&content) {
                if !process_non_interactive_message(
                    &prompt,
                    &provider,
                    &agent_config,
                    &available_tools,
                    &mut conversation,
                    &session_id,
                    &mut stdout,
                )
                .await?
                {
                    return Ok(());
                }
            }
        } else if agent_config.input_format == "text" {
            // Text mode: read ALL of stdin until EOF as a single user message.
            // (JSON mode below preserves line-per-message semantics.) This
            // mirrors the TS/Scala behavior so multi-line context piped into
            // the agent reaches it as one turn, not one turn per line.
            use std::io::Read;
            let mut user_content = String::new();
            io::stdin().read_to_string(&mut user_content)?;
            let trimmed = user_content.trim_end_matches('\n').to_string();
            if !trimmed.is_empty() {
                process_non_interactive_message(
                    &trimmed,
                    &provider,
                    &agent_config,
                    &available_tools,
                    &mut conversation,
                    &session_id,
                    &mut stdout,
                )
                .await?;
            }
        } else {
            let stdin = io::stdin();
            for line in stdin.lock().lines() {
                let raw_line = line?;
                let user_content = match serde_json::from_str::<InputLine>(&raw_line) {
                    Ok(parsed) => parsed.content,
                    Err(_) => raw_line,
                };

                if !process_non_interactive_message(
                    &user_content,
                    &provider,
                    &agent_config,
                    &available_tools,
                    &mut conversation,
                    &session_id,
                    &mut stdout,
                )
                .await?
                {
                    return Ok(());
                }
            }
        }
    }

    Ok(())
}

#[tokio::main]
pub(crate) async fn run() {
    let result = run_inner().await;
    if let Err(e) = result {
        eprintln!("{e:#}");
        std::process::exit(1);
    }
}
