// Scaffolding: AgentConfig type, CLI parsing, defaults, resolution. Attendees do not edit this file.

use std::{
    env, fs,
    path::{Path, PathBuf},
};

use anyhow::{bail, Result};
use serde_json::Value;

use crate::tools::{ToolName, ToolSelection};

const DEFAULT_SECRET_PATTERNS: &[&str] = &[
    "(?i)api[_-]?key\\s*[:=]\\s*\\S+",
    "(?i)secret\\s*[:=]\\s*\\S+",
    "(?i)password\\s*[:=]\\s*\\S+",
    "(?i)token\\s*[:=]\\s*\\S+",
    "sk-[a-zA-Z0-9]{20,}",
    "ghp_[a-zA-Z0-9]{36,}",
];

#[derive(Debug, Clone)]
pub struct AgentConfig {
    pub(crate) model: String,
    pub(crate) system_prompt: PathBuf,
    pub(crate) role_prompt: Option<PathBuf>,
    pub(crate) tools: ToolSelection,
    pub(crate) work_dir: PathBuf,
    pub(crate) max_iterations: usize,
    pub(crate) temperature: f32,
    pub(crate) verbose: bool,
    pub(crate) instructions: Option<PathBuf>,
    pub(crate) skills_dir: Option<PathBuf>,
    pub(crate) history_dir: Option<PathBuf>,
    pub(crate) commands_dir: Option<PathBuf>,
    pub(crate) max_context_chars: Option<usize>,
    pub(crate) allow_tools: Vec<String>,
    pub(crate) deny_tools: Vec<String>,
    pub(crate) protected_files: Vec<String>,
    pub(crate) secret_patterns: Vec<String>,
    pub(crate) audit_log: Option<PathBuf>,
    pub(crate) sandbox_vm: bool,
    pub(crate) input_files: Vec<PathBuf>,
    pub(crate) output_file: Option<PathBuf>,
    pub(crate) input_format: String,
    pub(crate) output_format: String,
    /// Decorator routing — see TS counterpart for the full contract. When
    /// `Some`, every decorator's `appliesTo` sees this as
    /// `AgentState::current_phase`; when `None`, falls back to basename of
    /// `role_prompt`. Callers materializing role-prompts to temp files MUST
    /// set this.
    pub current_phase: Option<String>,
    /// Exit gates: shell commands that must each exit 0 before the agent is
    /// allowed to terminate via `message_user`. The exit-gate decorator runs
    /// them in `work_dir` via `sh -c`; a non-zero exit becomes a Deny on
    /// message_user and the LLM gets another turn (with the gate output in
    /// the deny reason) to fix the underlying failure. Empty by default.
    pub exit_gates: Vec<String>,
}

impl AgentConfig {
    pub fn default_config() -> Self {
        let work_dir = env::current_dir().unwrap_or_else(|_| PathBuf::from("."));

        Self {
            model: env::var("MODEL").unwrap_or_else(|_| "anthropic/claude-sonnet-4".to_string()),
            system_prompt: PathBuf::from("../system-prompt.txt"),
            role_prompt: None,
            tools: ToolSelection::All,
            work_dir,
            max_iterations: 20,
            temperature: 0.0,
            verbose: false,
            instructions: None,
            skills_dir: None,
            history_dir: None,
            commands_dir: None,
            max_context_chars: None,
            allow_tools: vec![],
            deny_tools: vec![],
            protected_files: vec![],
            secret_patterns: DEFAULT_SECRET_PATTERNS
                .iter()
                .map(|s| s.to_string())
                .collect(),
            audit_log: None,
            sandbox_vm: false,
            input_files: vec![],
            output_file: None,
            input_format: "json".to_string(),
            output_format: "json".to_string(),
            current_phase: None,
            exit_gates: vec![],
        }
    }
}

#[derive(Debug, Clone, Default)]
pub(crate) enum RequestedMode {
    #[default]
    Auto,
    Interactive,
    Protocol,
    File(PathBuf),
}

#[derive(Debug, Default)]
pub(crate) struct CliConfig {
    pub(crate) model: Option<String>,
    pub(crate) system_prompt: Option<PathBuf>,
    pub(crate) role_prompt: Option<PathBuf>,
    pub(crate) tools: Option<ToolSelection>,
    pub(crate) work_dir: Option<PathBuf>,
    pub(crate) max_iterations: Option<usize>,
    pub(crate) temperature: Option<f32>,
    pub(crate) verbose: bool,
    pub(crate) instructions: Option<PathBuf>,
    pub(crate) skills_dir: Option<PathBuf>,
    pub(crate) history_dir: Option<PathBuf>,
    pub(crate) resume_session_id: Option<String>,
    pub(crate) commands_dir: Option<PathBuf>,
    pub(crate) max_context_chars: Option<usize>,
    pub(crate) allow_tools: Option<Vec<String>>,
    pub(crate) deny_tools: Option<Vec<String>>,
    pub(crate) protected_files: Option<Vec<String>>,
    pub(crate) secret_patterns: Option<Vec<String>>,
    pub(crate) audit_log: Option<PathBuf>,
    pub(crate) sandbox_vm: bool,
    pub(crate) input_files: Option<Vec<PathBuf>>,
    pub(crate) output_file: Option<PathBuf>,
    pub(crate) input_format: Option<String>,
    pub(crate) output_format: Option<String>,
    pub(crate) requested_mode: RequestedMode,
    pub(crate) exit_gates: Option<Vec<String>>,
}

fn parse_io_format(value: &str, flag: &str) -> Result<String> {
    if value == "json" || value == "text" {
        Ok(value.to_string())
    } else {
        bail!(
            "Invalid value for {flag}: {value} (must be json or text)",
            flag = flag,
            value = value
        )
    }
}

pub(crate) fn parse_tool_names(names: &[String]) -> Result<Vec<ToolName>> {
    let mut unknown = Vec::new();
    let mut parsed = Vec::new();

    for name in names {
        if let Some(tool_name) = ToolName::from_str(name) {
            parsed.push(tool_name);
        } else {
            unknown.push(name.clone());
        }
    }

    if unknown.is_empty() {
        Ok(parsed)
    } else {
        bail!("Unknown tool name(s): {}", unknown.join(", "))
    }
}

fn parse_tool_selection_csv(raw: &str) -> Result<ToolSelection> {
    let names = raw
        .split(',')
        .map(str::trim)
        .filter(|name| !name.is_empty())
        .map(ToString::to_string)
        .collect::<Vec<_>>();

    if names.is_empty() {
        Ok(ToolSelection::Only(vec![]))
    } else {
        Ok(ToolSelection::Only(parse_tool_names(&names)?))
    }
}

fn set_mode_flag(
    first_mode_flag: &mut Option<&'static str>,
    next_mode_flag: &'static str,
) -> Result<()> {
    if let Some(first) = *first_mode_flag {
        bail!("Conflicting mode flags: {first} and {next_mode_flag}");
    }
    *first_mode_flag = Some(next_mode_flag);

    Ok(())
}

fn all_strings(arr: &[Value]) -> Option<Vec<String>> {
    let strings: Vec<_> = arr.iter().map(|v| v.as_str().map(String::from)).collect();
    if strings.iter().all(Option::is_some) {
        Some(strings.into_iter().flatten().collect())
    } else {
        None
    }
}

pub(crate) fn load_config_file(path: &str) -> Result<CliConfig> {
    let content = fs::read_to_string(path)?;
    let value: Value = serde_json::from_str(&content)?;
    let mut cfg = CliConfig::default();
    let config_path = if Path::new(path).is_absolute() {
        PathBuf::from(path)
    } else {
        env::current_dir()
            .unwrap_or_else(|_| PathBuf::from("."))
            .join(path)
    };
    let config_dir = config_path
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));
    let resolve_config_path = |raw: &str| -> PathBuf {
        let path = PathBuf::from(raw);
        if path.is_absolute() {
            path
        } else {
            config_dir.join(path)
        }
    };

    if let Some(obj) = value.as_object() {
        cfg.model = obj.get("model").and_then(|v| v.as_str()).map(String::from);
        cfg.system_prompt = obj
            .get("systemPrompt")
            .and_then(|v| v.as_str())
            .map(resolve_config_path);
        cfg.role_prompt = obj
            .get("rolePrompt")
            .and_then(|v| v.as_str())
            .map(resolve_config_path);
        if let Some(tool_values) = obj.get("tools").and_then(|v| v.as_array()) {
            let tool_names = tool_values
                .iter()
                .filter_map(|v| v.as_str().map(ToString::to_string))
                .collect::<Vec<_>>();
            cfg.tools = Some(if tool_names.is_empty() {
                ToolSelection::All
            } else {
                ToolSelection::Only(parse_tool_names(&tool_names)?)
            });
        }
        cfg.work_dir = obj
            .get("workDir")
            .and_then(|v| v.as_str())
            .map(resolve_config_path);
        cfg.max_iterations = obj
            .get("maxIterations")
            .and_then(|v| v.as_u64())
            .map(|n| n as usize);
        cfg.temperature = obj
            .get("temperature")
            .and_then(|v| v.as_f64())
            .map(|n| n as f32);
        cfg.verbose = obj
            .get("verbose")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        cfg.instructions = obj
            .get("instructions")
            .and_then(|v| v.as_str())
            .map(resolve_config_path);
        cfg.skills_dir = obj
            .get("skillsDir")
            .and_then(|v| v.as_str())
            .map(resolve_config_path);
        cfg.history_dir = obj
            .get("historyDir")
            .and_then(|v| v.as_str())
            .map(resolve_config_path);
        cfg.commands_dir = obj
            .get("commandsDir")
            .and_then(|v| v.as_str())
            .map(resolve_config_path);
        cfg.max_context_chars = obj
            .get("maxContextChars")
            .and_then(|v| v.as_u64())
            .map(|n| n as usize);
        cfg.allow_tools = obj
            .get("allowTools")
            .and_then(|v| v.as_array())
            .and_then(|a| all_strings(a));
        cfg.deny_tools = obj
            .get("denyTools")
            .and_then(|v| v.as_array())
            .and_then(|a| all_strings(a));
        cfg.protected_files = obj
            .get("protectedFiles")
            .and_then(|v| v.as_array())
            .and_then(|a| all_strings(a));
        cfg.secret_patterns = obj
            .get("secretPatterns")
            .and_then(|v| v.as_array())
            .and_then(|a| all_strings(a));
        cfg.audit_log = obj
            .get("auditLog")
            .and_then(|v| v.as_str())
            .map(resolve_config_path);
        cfg.input_files = obj
            .get("inputFiles")
            .and_then(|v| v.as_array())
            .and_then(|arr| all_strings(arr))
            .map(|paths| paths.into_iter().map(|p| resolve_config_path(&p)).collect());
        cfg.output_file = obj
            .get("outputFile")
            .and_then(|v| v.as_str())
            .map(resolve_config_path);
        cfg.input_format = obj
            .get("inputFormat")
            .and_then(|v| v.as_str())
            .and_then(|v| (v == "json" || v == "text").then_some(v.to_string()));
        cfg.output_format = obj
            .get("outputFormat")
            .and_then(|v| v.as_str())
            .and_then(|v| (v == "json" || v == "text").then_some(v.to_string()));
        cfg.exit_gates = obj
            .get("exitGates")
            .and_then(|v| v.as_array())
            .and_then(|a| all_strings(a));
    }

    Ok(cfg)
}

pub(crate) fn parse_cli_config(args: &[String]) -> Result<CliConfig> {
    let mut parsed = CliConfig::default();
    let mut config_file: Option<CliConfig> = None;
    let mut first_mode_flag: Option<&'static str> = None;
    let mut i = 0;

    while i < args.len() {
        match args[i].as_str() {
            "--config" => {
                i += 1;
                if i >= args.len() {
                    bail!("--config requires a value");
                }
                config_file = Some(load_config_file(&args[i])?);
            }
            "--model" => {
                i += 1;
                if i >= args.len() {
                    bail!("--model requires a value");
                }
                parsed.model = Some(args[i].clone());
            }
            "--prompt" => {
                i += 1;
                if i >= args.len() {
                    bail!("--prompt requires a value");
                }
                parsed.system_prompt = Some(PathBuf::from(&args[i]));
            }
            "--role-prompt" => {
                i += 1;
                if i >= args.len() {
                    bail!("--role-prompt requires a value");
                }
                parsed.role_prompt = Some(PathBuf::from(&args[i]));
            }
            "--tools" => {
                i += 1;
                if i >= args.len() {
                    bail!("--tools requires a value");
                }
                parsed.tools = Some(parse_tool_selection_csv(&args[i])?);
            }
            "--work-dir" => {
                i += 1;
                if i >= args.len() {
                    bail!("--work-dir requires a value");
                }
                parsed.work_dir = Some(PathBuf::from(&args[i]));
            }
            "--max-iterations" => {
                i += 1;
                if i >= args.len() {
                    bail!("--max-iterations requires a value");
                }
                parsed.max_iterations = Some(args[i].parse()?);
            }
            "--temperature" => {
                i += 1;
                if i >= args.len() {
                    bail!("--temperature requires a value");
                }
                parsed.temperature = Some(args[i].parse()?);
            }
            "--verbose" => {
                parsed.verbose = true;
            }
            "--file" => {
                i += 1;
                if i >= args.len() {
                    bail!("--file requires a value");
                }
                set_mode_flag(&mut first_mode_flag, "--file")?;
                parsed.requested_mode = RequestedMode::File(PathBuf::from(&args[i]));
            }
            "--instructions" => {
                i += 1;
                if i >= args.len() {
                    bail!("--instructions requires a value");
                }
                parsed.instructions = Some(PathBuf::from(&args[i]));
            }
            "--skills-dir" => {
                i += 1;
                if i >= args.len() {
                    bail!("--skills-dir requires a value");
                }
                parsed.skills_dir = Some(PathBuf::from(&args[i]));
            }
            "--history-dir" => {
                i += 1;
                if i >= args.len() {
                    bail!("--history-dir requires a value");
                }
                parsed.history_dir = Some(PathBuf::from(&args[i]));
            }
            "--resume" => {
                i += 1;
                if i >= args.len() {
                    bail!("--resume requires a value");
                }
                parsed.resume_session_id = Some(args[i].clone());
            }
            "--commands-dir" => {
                i += 1;
                if i >= args.len() {
                    bail!("--commands-dir requires a value");
                }
                parsed.commands_dir = Some(PathBuf::from(&args[i]));
            }
            "--max-context-chars" => {
                i += 1;
                if i >= args.len() {
                    bail!("--max-context-chars requires a value");
                }
                parsed.max_context_chars = Some(args[i].parse()?);
            }
            "--allow-tools" => {
                i += 1;
                if i >= args.len() {
                    bail!("--allow-tools requires a value");
                }
                parsed.allow_tools = Some(
                    args[i]
                        .split(',')
                        .map(|s| s.trim().to_string())
                        .filter(|s| !s.is_empty())
                        .collect(),
                );
            }
            "--deny-tools" => {
                i += 1;
                if i >= args.len() {
                    bail!("--deny-tools requires a value");
                }
                parsed.deny_tools = Some(
                    args[i]
                        .split(',')
                        .map(|s| s.trim().to_string())
                        .filter(|s| !s.is_empty())
                        .collect(),
                );
            }
            "--protected-files" => {
                i += 1;
                if i >= args.len() {
                    bail!("--protected-files requires a value");
                }
                parsed.protected_files = Some(
                    args[i]
                        .split(',')
                        .map(|s| s.trim().to_string())
                        .filter(|s| !s.is_empty())
                        .collect(),
                );
            }
            "--secret-patterns" => {
                i += 1;
                if i >= args.len() {
                    bail!("--secret-patterns requires a value");
                }
                parsed.secret_patterns = Some(
                    args[i]
                        .split(',')
                        .map(|s| s.trim().to_string())
                        .filter(|s| !s.is_empty())
                        .collect(),
                );
            }
            "--audit-log" => {
                i += 1;
                if i >= args.len() {
                    bail!("--audit-log requires a value");
                }
                parsed.audit_log = Some(PathBuf::from(&args[i]));
            }
            "--sandbox-vm" => {
                parsed.sandbox_vm = true;
            }
            "--input-files" => {
                i += 1;
                if i >= args.len() {
                    bail!("--input-files requires a value");
                }
                parsed.input_files = Some(
                    args[i]
                        .split(',')
                        .map(|s| s.trim())
                        .filter(|s| !s.is_empty())
                        .map(PathBuf::from)
                        .collect(),
                );
            }
            "--output-file" => {
                i += 1;
                if i >= args.len() {
                    bail!("--output-file requires a value");
                }
                parsed.output_file = Some(PathBuf::from(&args[i]));
            }
            "--input-format" => {
                i += 1;
                if i >= args.len() {
                    bail!("--input-format requires a value");
                }
                parsed.input_format = Some(parse_io_format(&args[i], "--input-format")?);
            }
            "--output-format" => {
                i += 1;
                if i >= args.len() {
                    bail!("--output-format requires a value");
                }
                parsed.output_format = Some(parse_io_format(&args[i], "--output-format")?);
            }
            "--interactive" => {
                set_mode_flag(&mut first_mode_flag, "--interactive")?;
                parsed.requested_mode = RequestedMode::Interactive;
            }
            "--protocol" => {
                set_mode_flag(&mut first_mode_flag, "--protocol")?;
                parsed.requested_mode = RequestedMode::Protocol;
            }
            "--exit-gate" => {
                // Repeatable: each occurrence appends one shell command.
                // The exit-gate decorator gates `message_user` on these.
                i += 1;
                if i >= args.len() {
                    bail!("missing value for --exit-gate");
                }
                parsed
                    .exit_gates
                    .get_or_insert_with(Vec::new)
                    .push(args[i].clone());
            }
            _ => {}
        }
        i += 1;
    }

    if let Some(mut from_file) = config_file {
        macro_rules! overlay {
            ($field:ident) => {
                if parsed.$field.is_some() {
                    from_file.$field = parsed.$field;
                }
            };
        }
        overlay!(model);
        overlay!(system_prompt);
        overlay!(role_prompt);
        overlay!(tools);
        overlay!(work_dir);
        overlay!(max_iterations);
        overlay!(temperature);
        overlay!(instructions);
        overlay!(skills_dir);
        overlay!(history_dir);
        overlay!(commands_dir);
        overlay!(max_context_chars);
        overlay!(allow_tools);
        overlay!(deny_tools);
        overlay!(protected_files);
        overlay!(secret_patterns);
        overlay!(audit_log);
        overlay!(input_files);
        overlay!(output_file);
        overlay!(input_format);
        overlay!(output_format);
        overlay!(exit_gates);
        if parsed.verbose {
            from_file.verbose = true;
        }
        if !matches!(parsed.requested_mode, RequestedMode::Auto) {
            from_file.requested_mode = parsed.requested_mode;
        }
        Ok(from_file)
    } else {
        Ok(parsed)
    }
}

pub(crate) fn resolve_config(overrides: &CliConfig) -> AgentConfig {
    let mut config = AgentConfig::default_config();

    if let Some(model) = &overrides.model {
        config.model = model.clone();
    }
    if let Some(system_prompt) = &overrides.system_prompt {
        config.system_prompt = system_prompt.clone();
    }
    if let Some(role_prompt) = &overrides.role_prompt {
        config.role_prompt = Some(role_prompt.clone());
    }
    if let Some(tools) = &overrides.tools {
        config.tools = tools.clone();
    }
    if let Some(work_dir) = &overrides.work_dir {
        config.work_dir = work_dir.clone();
    }
    if let Some(max_iterations) = overrides.max_iterations {
        config.max_iterations = max_iterations;
    }
    if let Some(temperature) = overrides.temperature {
        config.temperature = temperature;
    }
    if let Some(instructions) = &overrides.instructions {
        config.instructions = Some(instructions.clone());
    }
    if let Some(skills_dir) = &overrides.skills_dir {
        config.skills_dir = Some(skills_dir.clone());
    }
    if let Some(history_dir) = &overrides.history_dir {
        config.history_dir = Some(history_dir.clone());
    }
    if let Some(commands_dir) = &overrides.commands_dir {
        config.commands_dir = Some(commands_dir.clone());
    }
    if let Some(max_context_chars) = overrides.max_context_chars {
        config.max_context_chars = Some(max_context_chars);
    }
    if let Some(allow_tools) = &overrides.allow_tools {
        config.allow_tools = allow_tools.clone();
    }
    if let Some(deny_tools) = &overrides.deny_tools {
        config.deny_tools = deny_tools.clone();
    }
    if let Some(protected_files) = &overrides.protected_files {
        config.protected_files = protected_files.clone();
    }
    if let Some(secret_patterns) = &overrides.secret_patterns {
        config.secret_patterns = secret_patterns.clone();
    }
    if let Some(audit_log) = &overrides.audit_log {
        config.audit_log = Some(audit_log.clone());
    }
    if let Some(input_files) = &overrides.input_files {
        if !input_files.is_empty() {
            config.input_files = input_files.clone();
        }
    }
    if let Some(output_file) = &overrides.output_file {
        config.output_file = Some(output_file.clone());
    }
    if let Some(input_format) = &overrides.input_format {
        config.input_format = input_format.clone();
    }
    if let Some(output_format) = &overrides.output_format {
        config.output_format = output_format.clone();
    }
    config.verbose = overrides.verbose || config.verbose;
    config.sandbox_vm = overrides.sandbox_vm || config.sandbox_vm;
    if let Some(exit_gates) = &overrides.exit_gates {
        config.exit_gates = exit_gates.clone();
    }

    config
}
