// Scaffolding: Conversation types, ChatProvider, message construction. Attendees do not edit this file.

// ---------------------------------------------------------------------------
// Conversation types and helpers (scaffolding)
// ---------------------------------------------------------------------------

use std::ops::Index;

use anyhow::{bail, Result};
pub(crate) use async_openai::types::{
    ChatCompletionRequestAssistantMessageArgs, ChatCompletionRequestMessage,
    ChatCompletionRequestSystemMessageArgs, ChatCompletionRequestUserMessageArgs,
    CreateChatCompletionRequestArgs,
};
use serde_json::Value;

use crate::tools::{RawToolCall, ToolName};

/// Result of a single agent turn: the final response content and ordered tool calls.
pub(crate) struct TurnResult {
    pub(crate) content: String,
    pub(crate) tool_calls: Vec<ToolName>,
}

pub(crate) struct Conversation {
    pub(crate) system: ChatCompletionRequestMessage,
    pub(crate) turns: Vec<ChatCompletionRequestMessage>,
}

impl Conversation {
    pub(crate) fn new(system_content: String) -> Self {
        Self {
            system: ChatCompletionRequestSystemMessageArgs::default()
                .content(system_content)
                .build()
                .expect("system message should build")
                .into(),
            turns: Vec::new(),
        }
    }

    pub(crate) fn push(&mut self, msg: ChatCompletionRequestMessage) {
        self.turns.push(msg);
    }

    pub(crate) fn as_messages(&self) -> Vec<ChatCompletionRequestMessage> {
        let mut messages = Vec::with_capacity(self.turns.len() + 1);
        messages.push(self.system.clone());
        messages.extend(self.turns.iter().cloned());
        messages
    }

    pub(crate) fn len(&self) -> usize {
        1 + self.turns.len()
    }
}

impl Index<usize> for Conversation {
    type Output = ChatCompletionRequestMessage;

    fn index(&self, index: usize) -> &Self::Output {
        if index == 0 {
            &self.system
        } else {
            &self.turns[index - 1]
        }
    }
}

impl<'a> IntoIterator for &'a Conversation {
    type Item = &'a ChatCompletionRequestMessage;
    type IntoIter = std::iter::Chain<
        std::iter::Once<&'a ChatCompletionRequestMessage>,
        std::slice::Iter<'a, ChatCompletionRequestMessage>,
    >;

    fn into_iter(self) -> Self::IntoIter {
        std::iter::once(&self.system).chain(self.turns.iter())
    }
}

#[async_trait::async_trait(?Send)]
pub(crate) trait ChatProvider {
    async fn complete(&self, messages: &[ChatCompletionRequestMessage]) -> Result<String>;
}

pub(crate) struct ParseResult {
    pub(crate) calls: Vec<RawToolCall>,
    pub(crate) errors: Vec<String>,
}

fn text_content_from_json(value: &Value) -> String {
    match value {
        Value::String(text) => text.clone(),
        Value::Array(items) => items
            .iter()
            .filter_map(|item| item.get("text").and_then(Value::as_str))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => String::new(),
    }
}

pub(crate) fn message_role_and_content(
    message: &ChatCompletionRequestMessage,
) -> Option<(String, String)> {
    let value = serde_json::to_value(message).ok()?;
    let role = value.get("role")?.as_str()?.to_string();
    let content = value
        .get("content")
        .map(text_content_from_json)
        .unwrap_or_default();
    Some((role, content))
}

pub(crate) fn build_message(role: &str, content: &str) -> Result<ChatCompletionRequestMessage> {
    match role {
        "system" => Ok(ChatCompletionRequestSystemMessageArgs::default()
            .content(content)
            .build()?
            .into()),
        "user" => Ok(ChatCompletionRequestUserMessageArgs::default()
            .content(content)
            .build()?
            .into()),
        "assistant" => Ok(ChatCompletionRequestAssistantMessageArgs::default()
            .content(content)
            .build()?
            .into()),
        other => bail!("unsupported message role: {other}"),
    }
}
