// Scaffolding: code-decorator types (AgentState, ToolDecorator, allow/deny, snapshotAgentState). Attendees do not edit this file.

// Code-decorator types. A ToolDecorator is a value, not a config file —
// each consumer (agent core or an external workflow) assembles a list
// of decorators and passes them into run_phase / handle_turn.
//
// Decorators run inside the tool-execution loop:
//   before — inspect/transform an outgoing ToolInvocation; may Allow (with
//            optionally-modified invocation) or Deny (reason → tool result
//            → fed back to the LLM on the next turn).
//   after  — inspect a returned ToolResult; same Allow/Deny outcome (Deny
//            replaces the tool result with the deny reason).
//
// AgentState is an immutable snapshot the loop hands to each decorator.

use std::future::Future;
use std::path::PathBuf;
use std::pin::Pin;
use std::sync::Arc;

use serde_json::Value;

use crate::config::AgentConfig;
use crate::tools::ToolResult;

#[derive(Debug, Clone)]
pub struct ToolInvocation {
    pub name: String,
    /// Tool arguments as a JSON value. Usually a JSON object; decorators that
    /// want to rewrite fields should match on `Value::Object(..)`.
    pub arguments: Value,
}

#[derive(Debug, Clone)]
pub struct AgentStateMessage {
    pub role: String,
    pub content: String,
}

#[derive(Debug, Clone)]
pub struct AgentState {
    /// Conversation messages (role + content) up to but not including the
    /// current tool result.
    pub conversation: Vec<AgentStateMessage>,
    /// Tool names enabled for this turn.
    pub enabled_tools: Vec<String>,
    /// Rough token usage (chars/4 approximation; provider-reported once that lands).
    pub tokens_used: usize,
    /// Read-only snapshot of the agent config.
    pub config: AgentConfig,
    /// Current phase name (basename of role-prompt), or None when there is none.
    pub current_phase: Option<String>,
    /// Agent's working directory.
    pub work_dir: PathBuf,
}

#[derive(Debug, Clone)]
pub enum DecoratorOutcome {
    Allow { invocation: ToolInvocation },
    Deny { reason: String },
}

/// Constructor: Allow with the (possibly-rewritten) invocation.
pub fn allow(invocation: ToolInvocation) -> DecoratorOutcome {
    DecoratorOutcome::Allow { invocation }
}

/// Constructor: Deny with reason — short-circuits remaining decorators.
pub fn deny(reason: impl Into<String>) -> DecoratorOutcome {
    DecoratorOutcome::Deny {
        reason: reason.into(),
    }
}

/// Boxed async result type used by decorator function pointers. The double
/// indirection (Pin<Box<dyn Future>>) is the standard pattern for storing
/// async fn pointers in plain struct fields.
pub type DecoratorFuture<'a> = Pin<Box<dyn Future<Output = DecoratorOutcome> + 'a>>;

/// Function type for a decorator's `before` hook.
pub type BeforeFn =
    Arc<dyn for<'a> Fn(&'a ToolInvocation, &'a AgentState) -> DecoratorFuture<'a> + Send + Sync>;

/// Function type for a decorator's `after` hook.
pub type AfterFn = Arc<
    dyn for<'a> Fn(&'a ToolInvocation, &'a ToolResult, &'a AgentState) -> DecoratorFuture<'a>
        + Send
        + Sync,
>;

/// Sync `appliesTo` filter — false skips the decorator entirely.
pub type AppliesToFn = Arc<dyn Fn(&ToolInvocation, &AgentState) -> bool + Send + Sync>;

#[derive(Clone)]
pub struct ToolDecorator {
    pub name: String,
    pub applies_to: AppliesToFn,
    pub before: Option<BeforeFn>,
    pub after: Option<AfterFn>,
}

impl std::fmt::Debug for ToolDecorator {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ToolDecorator")
            .field("name", &self.name)
            .field("has_before", &self.before.is_some())
            .field("has_after", &self.after.is_some())
            .finish()
    }
}

/// Build an AgentState snapshot from the loop's current values. The Conversation
/// is summarized to role+content pairs to keep AgentState transport-agnostic
/// (decorators don't see the underlying ChatCompletionRequestMessage type).
/// `tokens_used` is a char/4 approximation of the conversation total.
pub fn snapshot_agent_state(
    messages: Vec<AgentStateMessage>,
    enabled_tools: Vec<String>,
    config: AgentConfig,
    current_phase: Option<String>,
    work_dir: PathBuf,
) -> AgentState {
    let total_chars: usize = messages.iter().map(|m| m.content.len()).sum();
    AgentState {
        conversation: messages,
        enabled_tools,
        tokens_used: total_chars.div_ceil(4),
        config,
        current_phase,
        work_dir,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn empty_state() -> AgentState {
        snapshot_agent_state(
            Vec::new(),
            Vec::new(),
            AgentConfig::default_config(),
            None,
            PathBuf::from("/tmp"),
        )
    }

    #[test]
    fn allow_carries_invocation() {
        let inv = ToolInvocation {
            name: "read_file".to_string(),
            arguments: serde_json::json!({}),
        };
        let out = allow(inv.clone());
        match out {
            DecoratorOutcome::Allow { invocation } => assert_eq!(invocation.name, inv.name),
            _ => panic!("expected Allow"),
        }
    }

    #[test]
    fn deny_carries_reason() {
        let out = deny("nope");
        match out {
            DecoratorOutcome::Deny { reason } => assert_eq!(reason, "nope"),
            _ => panic!("expected Deny"),
        }
    }

    #[test]
    fn snapshot_propagates_fields() {
        let state = snapshot_agent_state(
            vec![AgentStateMessage {
                role: "user".to_string(),
                content: "hello".to_string(),
            }],
            vec!["read_file".to_string(), "shell".to_string()],
            AgentConfig::default_config(),
            Some("spec".to_string()),
            PathBuf::from("/tmp/agent"),
        );
        assert_eq!(state.current_phase.as_deref(), Some("spec"));
        assert_eq!(state.work_dir, PathBuf::from("/tmp/agent"));
        assert_eq!(state.enabled_tools, vec!["read_file", "shell"]);
        assert_eq!(state.conversation.len(), 1);
    }

    #[test]
    fn snapshot_approximates_tokens() {
        let state = snapshot_agent_state(
            vec![
                AgentStateMessage {
                    role: "system".to_string(),
                    content: "x".repeat(16),
                },
                AgentStateMessage {
                    role: "user".to_string(),
                    content: "y".repeat(16),
                },
            ],
            Vec::new(),
            AgentConfig::default_config(),
            None,
            PathBuf::from("/"),
        );
        assert_eq!(state.tokens_used, 8); // 32 chars / 4
    }

    #[test]
    fn snapshot_exposes_supplied_values_at_call_time() {
        // The agent loop builds the snapshot once per tool call and never
        // re-issues it mid-call. This test asserts the snapshot owns its
        // captured data (Rust ownership makes source mutation harmless,
        // but we still verify the fields the decorator observes).
        let mut messages = vec![AgentStateMessage {
            role: "user".to_string(),
            content: "first".to_string(),
        }];
        let state = snapshot_agent_state(
            messages.clone(),
            vec!["read_file".to_string()],
            AgentConfig::default_config(),
            Some("spec".to_string()),
            PathBuf::from("/tmp/x"),
        );
        // Mutate the source vector after the snapshot — snapshot is unchanged.
        messages.push(AgentStateMessage {
            role: "assistant".to_string(),
            content: "later".to_string(),
        });
        assert_eq!(state.conversation.len(), 1);
        assert_eq!(state.current_phase.as_deref(), Some("spec"));
        assert_eq!(state.work_dir, PathBuf::from("/tmp/x"));
        assert_eq!(state.enabled_tools, vec!["read_file"]);
    }

    #[test]
    fn tool_decorator_value_constructs() {
        use std::pin::Pin;
        let dec = ToolDecorator {
            name: "passthrough".to_string(),
            applies_to: Arc::new(|_inv, _state| true),
            before: Some(Arc::new(
                |inv, _state| -> Pin<Box<dyn Future<Output = DecoratorOutcome>>> {
                    Box::pin(async move { allow(inv.clone()) })
                },
            )),
            after: None,
        };
        assert_eq!(dec.name, "passthrough");
        let state = empty_state();
        let inv = ToolInvocation {
            name: "read_file".to_string(),
            arguments: serde_json::json!({}),
        };
        assert!((dec.applies_to)(&inv, &state));
    }
}
