// Scaffolding: in-process library entry point (run_phase, RunPhaseOptions). Attendees do not edit this file.

// In-process library entry point. The CLI in agent::run wraps these for
// terminal use; workflow tools import run_phase()
// directly to drive the agent loop with their own orchestration.
// No CLI parsing, no stdin/stdout protocol, no interactive mode —
// just "run one phase to completion."

pub(crate) mod agent;
pub mod config;
pub(crate) mod conversation;
pub mod decorators;
pub(crate) mod exercises;
pub(crate) mod session;
pub(crate) mod terminal;
pub mod tools;

#[cfg(test)]
mod tests;

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, bail, Result};
use async_openai::config::OpenAIConfig;
use async_openai::types::{ChatCompletionRequestMessage, CreateChatCompletionRequestArgs};
use async_openai::Client;
use async_trait::async_trait;

use crate::config::AgentConfig;
use crate::conversation::{ChatProvider, Conversation};
use crate::decorators::ToolDecorator;
use crate::exercises::{build_system_prompt, handle_turn};
use crate::tools::{get_enabled_tools, ToolName, ToolSelection};

/// Public phase options for in-process workflow orchestrators.
/// All fields except `user_message` have sensible defaults.
pub struct RunPhaseOptions {
    /// Model identifier (e.g. "anthropic/claude-sonnet-4"). None = env MODEL or library default.
    pub model: Option<String>,
    /// Absolute path to the system prompt template. None = agent/system-prompt.txt.
    pub system_prompt_path: Option<PathBuf>,
    /// Inline role prompt text. Materialized to a temp file because
    /// build_system_prompt reads role_prompt as a path.
    pub role_prompt_text: String,
    /// Tool names to enable (e.g. ["read_file", "shell", "message_user"]).
    pub tools: Vec<String>,
    pub max_iterations: usize,
    pub temperature: f32,
    pub deny_tools: Vec<String>,
    pub work_dir: PathBuf,
    pub input_files: Vec<PathBuf>,
    pub output_file: Option<PathBuf>,
    pub user_message: String,
    /// Override OPENROUTER_API_KEY (default: read from env).
    pub api_key: Option<String>,
    /// Override OpenRouter base URL.
    pub base_url: Option<String>,
    /// Code decorators applied in the tool-execution loop. Empty list = no-op.
    pub decorators: Vec<ToolDecorator>,
    /// Phase name handed to every decorator's `appliesTo` via
    /// `AgentState::current_phase`. Set this to the phase id whenever you
    /// have it — basename-of-role_prompt is an unreliable fallback when the
    /// role-prompt is materialized to a temp file (which this very function
    /// does below).
    pub phase: Option<String>,
}

pub struct RunPhaseResult {
    pub content: String,
    pub tool_calls: Vec<String>,
}

/// In-process provider for the chat completion API. Mirrors OpenRouterProvider
/// in agent.rs; duplicated here so lib.rs can stay independent of CLI types.
struct LibProvider {
    client: Client<OpenAIConfig>,
    model: String,
    temperature: f32,
}

#[async_trait(?Send)]
impl ChatProvider for LibProvider {
    async fn complete(&self, messages: &[ChatCompletionRequestMessage]) -> Result<String> {
        let request = CreateChatCompletionRequestArgs::default()
            .model(&self.model)
            .messages(messages.to_vec())
            .temperature(self.temperature)
            .max_tokens(4096_u16)
            .build()?;
        let response = self.client.chat().create(request).await?;
        Ok(response
            .choices
            .first()
            .and_then(|choice| choice.message.content.clone())
            .unwrap_or_default())
    }
}

/// Walk up to find system-prompt.txt next to the agent crate. Mirrors
/// the TS resolvePromptPath fallback ladder.
fn resolve_system_prompt(explicit: Option<&Path>) -> PathBuf {
    if let Some(p) = explicit {
        return p.to_path_buf();
    }
    let crate_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let candidates = [
        crate_root.join("..").join("system-prompt.txt"),
        crate_root.join("system-prompt.txt"),
    ];
    for c in &candidates {
        if c.exists() {
            return c.clone();
        }
    }
    candidates[0].clone()
}

fn glob_matches(pattern: &str, file_name: &str) -> bool {
    if !pattern.contains('*') {
        return pattern == file_name;
    }
    let mut parts = pattern.split('*').peekable();
    let mut rest = file_name;
    let first = parts.next().unwrap_or("");
    if !rest.starts_with(first) {
        return false;
    }
    rest = &rest[first.len()..];
    let mut last = "";
    let mut middle: Vec<&str> = Vec::new();
    while let Some(p) = parts.next() {
        if parts.peek().is_none() {
            last = p;
        } else {
            middle.push(p);
        }
    }
    for m in middle {
        if let Some(idx) = rest.find(m) {
            rest = &rest[idx + m.len()..];
        } else {
            return false;
        }
    }
    rest.ends_with(last)
}

fn augment_user_message(user_content: &str, input_files: &[PathBuf], work_dir: &Path) -> String {
    if input_files.is_empty() {
        return user_content.to_string();
    }
    let mut sections: Vec<String> = Vec::new();
    for file_pat in input_files {
        let resolved = if file_pat.is_absolute() {
            file_pat.clone()
        } else {
            work_dir.join(file_pat)
        };
        let dir = resolved.parent().unwrap_or_else(|| Path::new("."));
        let base = resolved.file_name().and_then(|s| s.to_str()).unwrap_or("");
        let files: Vec<PathBuf> = if base.contains('*') {
            if !dir.exists() {
                Vec::new()
            } else {
                let mut matched: Vec<PathBuf> = fs::read_dir(dir)
                    .map(|rd| {
                        rd.filter_map(|e| e.ok())
                            .filter(|e| {
                                e.file_name()
                                    .to_str()
                                    .map(|n| glob_matches(base, n))
                                    .unwrap_or(false)
                            })
                            .map(|e| e.path())
                            .collect()
                    })
                    .unwrap_or_default();
                matched.sort();
                matched
            }
        } else {
            vec![resolved]
        };
        for f in files {
            if f.is_file() {
                if let Ok(content) = fs::read_to_string(&f) {
                    let name = f.file_name().and_then(|s| s.to_str()).unwrap_or("");
                    sections.push(format!("--- {} ---\n{}", name, content));
                }
            }
        }
    }
    if sections.is_empty() {
        return user_content.to_string();
    }
    format!("{}\n\n{}", sections.join("\n\n"), user_content)
}

/// Run a single agent phase to completion. The caller supplies the inline
/// role prompt and tool list; this function handles provider construction,
/// system prompt assembly, conversation setup, input-file augmentation,
/// the agent loop, and output-file writing.
pub async fn run_phase(opts: RunPhaseOptions) -> Result<RunPhaseResult> {
    let api_key = opts
        .api_key
        .or_else(|| env::var("OPENROUTER_API_KEY").ok())
        .filter(|s| !s.is_empty())
        .ok_or_else(|| anyhow!("OPENROUTER_API_KEY not set"))?;

    let base_url = opts
        .base_url
        .unwrap_or_else(|| "https://openrouter.ai/api/v1".to_string());

    // Materialize the inline role prompt to a temp file: build_system_prompt
    // reads config.role_prompt as a path. This preserves the existing agent
    // contract without changing AgentConfig's shape.
    let tmp_dir = env::temp_dir();
    fs::create_dir_all(&tmp_dir).ok();
    let role_prompt_path = tmp_dir.join(format!(
        "phase-role-{}-{}.md",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0)
    ));
    fs::write(&role_prompt_path, &opts.role_prompt_text)?;

    // Parse tool name strings into the typed ToolSelection.
    let tool_names: Vec<ToolName> = opts
        .tools
        .iter()
        .filter_map(|s| ToolName::from_str(s))
        .collect();
    if tool_names.len() != opts.tools.len() {
        let bad: Vec<&String> = opts
            .tools
            .iter()
            .filter(|s| ToolName::from_str(s).is_none())
            .collect();
        bail!("Unknown tool name(s): {:?}", bad);
    }

    let mut agent_config = AgentConfig::default_config();
    if let Some(model) = opts.model {
        agent_config.model = model;
    }
    agent_config.system_prompt = resolve_system_prompt(opts.system_prompt_path.as_deref());
    agent_config.role_prompt = Some(role_prompt_path.clone());
    agent_config.tools = if tool_names.is_empty() {
        ToolSelection::All
    } else {
        ToolSelection::Only(tool_names)
    };
    agent_config.work_dir = opts.work_dir.clone();
    agent_config.max_iterations = opts.max_iterations;
    agent_config.temperature = opts.temperature;
    agent_config.deny_tools = opts.deny_tools;
    agent_config.input_files = opts.input_files.clone();
    agent_config.output_file = opts.output_file.clone();
    agent_config.input_format = "text".to_string();
    agent_config.output_format = "text".to_string();
    agent_config.current_phase = opts.phase.clone();

    let openai_cfg = OpenAIConfig::new()
        .with_api_key(api_key)
        .with_api_base(base_url);
    let client = Client::with_config(openai_cfg);
    let provider = LibProvider {
        client,
        model: agent_config.model.clone(),
        temperature: agent_config.temperature,
    };

    let all_tools = agent::tools();
    let enabled = get_enabled_tools(&agent_config, &all_tools);

    let mut conversation = Conversation::new(build_system_prompt(&agent_config, &enabled, false));

    let augmented = augment_user_message(
        &opts.user_message,
        &agent_config.input_files,
        &agent_config.work_dir,
    );

    let result = handle_turn(
        &provider,
        &agent_config,
        &enabled,
        &mut conversation,
        &augmented,
        None,
        &opts.decorators,
    )
    .await;

    // Best-effort cleanup of the temp prompt file regardless of outcome.
    let _ = fs::remove_file(&role_prompt_path);

    let result = result?;

    if let Some(out) = &agent_config.output_file {
        if let Some(parent) = out.parent() {
            if !parent.exists() {
                fs::create_dir_all(parent)?;
            }
        }
        fs::write(out, format!("{}\n", result.content))?;
    }

    Ok(RunPhaseResult {
        content: result.content,
        tool_calls: result
            .tool_calls
            .into_iter()
            .map(|t| t.as_str().to_string())
            .collect(),
    })
}

/// Public entry point for the CLI binary in src/main.rs.
pub fn run_cli() {
    agent::run();
}
