// Scaffolding: entry point shim. Attendees do not edit this file.

// Modules live in src/lib.rs (the library crate root). This binary is a thin
// entry point that delegates to the library's CLI runner.
fn main() {
    foundations_agent_rust::run_cli();
}
