// Scaffolding: session save/load + low-level frontmatter/file helpers. Attendees do not edit this file.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

pub(crate) fn session_file_path(history_dir: &Path, session_id: &str) -> PathBuf {
    history_dir.join(format!("{session_id}.json"))
}

pub(crate) fn format_timestamp_iso8601(time: SystemTime) -> String {
    let epoch_seconds = time
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let days_since_epoch = (epoch_seconds / 86_400) as i64;
    let seconds_of_day = epoch_seconds % 86_400;
    let (year, month, day) = civil_date_from_days_since_epoch(days_since_epoch);
    let hour = seconds_of_day / 3_600;
    let minute = (seconds_of_day % 3_600) / 60;
    let second = seconds_of_day % 60;

    format!("{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}Z")
}

// Howard Hinnant's civil_from_days algorithm for converting days since Unix epoch
// to a (year, month, day) triple. No external dependency needed.
fn civil_date_from_days_since_epoch(days_since_epoch: i64) -> (i32, u32, u32) {
    let z = days_since_epoch + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let day_of_era = z - era * 146_097;
    let year_of_era =
        (day_of_era - day_of_era / 1_460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let year = year_of_era + era * 400;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let month_prime = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * month_prime + 2) / 5 + 1;
    let month = month_prime + if month_prime < 10 { 3 } else { -9 };
    let year = year + if month <= 2 { 1 } else { 0 };

    (year as i32, month as u32, day as u32)
}

pub(crate) fn normalize_single_line(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

pub(crate) fn memories_file_path(work_dir: &Path) -> PathBuf {
    work_dir.join(".agent").join("memories.md")
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct StoredMessage {
    pub(crate) role: String,
    pub(crate) content: String,
}

#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct StoredSession {
    pub(crate) timestamp: String,
    #[serde(rename = "workDir")]
    pub(crate) work_dir: String,
    pub(crate) model: String,
    #[serde(rename = "systemPrompt", default)]
    pub(crate) system_prompt: String,
    pub(crate) turns: Vec<StoredMessage>,
}

pub(crate) const DEFAULT_SESSION_MODEL: &str = "anthropic/claude-sonnet-4";
pub(crate) const SESSION_TOPIC_CHAR_LIMIT: usize = 80;

fn strip_wrapping_quotes(value: &str) -> String {
    let trimmed = value.trim();
    if trimmed.len() >= 2
        && ((trimmed.starts_with('"') && trimmed.ends_with('"'))
            || (trimmed.starts_with('\'') && trimmed.ends_with('\'')))
    {
        trimmed[1..trimmed.len() - 1].to_string()
    } else {
        trimmed.to_string()
    }
}

pub(crate) fn parse_frontmatter(content: &str) -> (HashMap<String, String>, String) {
    let normalized = content.replace("\r\n", "\n");
    let lines = normalized.lines().collect::<Vec<_>>();

    if lines.first() != Some(&"---") {
        return (HashMap::new(), normalized);
    }

    let mut fields = HashMap::new();
    let mut closing_index = None;

    for (index, line) in lines.iter().enumerate().skip(1) {
        if *line == "---" {
            closing_index = Some(index);
            break;
        }

        if let Some((key, value)) = line.split_once(": ") {
            fields.insert(key.trim().to_string(), strip_wrapping_quotes(value));
        }
    }

    match closing_index {
        Some(index) => {
            let mut body_lines = lines[index + 1..].to_vec();
            if body_lines
                .first()
                .is_some_and(|line| line.trim().is_empty())
            {
                body_lines.remove(0);
            }
            (fields, body_lines.join("\n"))
        }
        None => (HashMap::new(), normalized),
    }
}
