// Scaffolding: terminal display + RecordingTerminal. Attendees do not edit this file.

// Interactive terminal renderer and test double. Spinner frames go to stderr to avoid
// corrupting protocol-mode stdout. NO_COLOR env var disables ANSI styling.
use crate::tools::{ToolName, ToolResult, ValidatedToolCall};
use serde_json::Value;
use std::{
    env,
    io::{self, Write},
    sync::{
        atomic::{AtomicBool, Ordering},
        Arc, Mutex,
    },
    thread::{self, JoinHandle},
    time::Duration,
};

// ---------------------------------------------------------------------------
// TerminalOutput trait
// ---------------------------------------------------------------------------

/// Presentation-only boundary for interactive mode. Implementations must not mutate
/// agent state. spinnerStart/spinnerStop are expected to be balanced lifecycle calls.
pub(crate) trait TerminalOutput {
    fn banner(&self, model: &str, tools: &[ToolName]);
    fn prompt_string(&self) -> String;
    fn thinking(&self, text: &str);
    fn tool_call(&self, call: &ValidatedToolCall);
    fn tool_result(&self, result: &ToolResult);
    fn answer(&self, text: &str);
    fn error(&self, text: &str);
    fn spinner_start(&self);
    fn spinner_stop(&self);
    fn goodbye(&self);
}

// ---------------------------------------------------------------------------
// TerminalEvent / RecordingTerminal (test helper)
// ---------------------------------------------------------------------------

#[cfg(test)]
pub(crate) use self::recording::*;

#[cfg(test)]
mod recording {
    use super::*;
    use std::cell::RefCell;

    #[derive(Debug, Clone)]
    #[allow(dead_code)]
    pub(crate) enum TerminalEvent {
        Banner { model: String, tools: Vec<ToolName> },
        Thinking(String),
        ToolCall { name: ToolName, args: Value },
        ToolResult { result: ToolResult },
        Answer(String),
        Error(String),
        SpinnerStart,
        SpinnerStop,
        Goodbye,
    }

    pub(crate) struct RecordingTerminal {
        events: RefCell<Vec<TerminalEvent>>,
    }

    impl RecordingTerminal {
        pub(crate) fn new() -> Self {
            Self {
                events: RefCell::new(Vec::new()),
            }
        }

        pub(crate) fn events(&self) -> Vec<TerminalEvent> {
            self.events.borrow().clone()
        }
    }

    impl TerminalOutput for RecordingTerminal {
        fn banner(&self, model: &str, tools: &[ToolName]) {
            self.events.borrow_mut().push(TerminalEvent::Banner {
                model: model.to_string(),
                tools: tools.to_vec(),
            });
        }

        fn prompt_string(&self) -> String {
            "> ".to_string()
        }

        fn thinking(&self, text: &str) {
            self.events
                .borrow_mut()
                .push(TerminalEvent::Thinking(text.to_string()));
        }

        fn tool_call(&self, call: &ValidatedToolCall) {
            self.events.borrow_mut().push(TerminalEvent::ToolCall {
                name: call.name,
                args: call.arguments.clone(),
            });
        }

        fn tool_result(&self, result: &ToolResult) {
            self.events.borrow_mut().push(TerminalEvent::ToolResult {
                result: result.clone(),
            });
        }

        fn answer(&self, text: &str) {
            self.events
                .borrow_mut()
                .push(TerminalEvent::Answer(text.to_string()));
        }

        fn error(&self, text: &str) {
            self.events
                .borrow_mut()
                .push(TerminalEvent::Error(text.to_string()));
        }

        fn spinner_start(&self) {
            self.events.borrow_mut().push(TerminalEvent::SpinnerStart);
        }

        fn spinner_stop(&self) {
            self.events.borrow_mut().push(TerminalEvent::SpinnerStop);
        }

        fn goodbye(&self) {
            self.events.borrow_mut().push(TerminalEvent::Goodbye);
        }
    }
}

// ---------------------------------------------------------------------------
// Tool call formatting (pure, testable)
// ---------------------------------------------------------------------------

const MAX_ARG_LINES: usize = 8;

fn format_arg_value(value: &Value) -> String {
    match value {
        Value::String(s) => {
            if s.contains('\n') {
                let lines: Vec<&str> = s.lines().collect();
                if lines.len() > MAX_ARG_LINES {
                    let shown: Vec<String> = lines[..MAX_ARG_LINES]
                        .iter()
                        .map(|l| format!("      {}", l))
                        .collect();
                    format!(
                        "|\n{}\n      [+{} more lines]",
                        shown.join("\n"),
                        lines.len() - MAX_ARG_LINES
                    )
                } else {
                    let indented: Vec<String> =
                        lines.iter().map(|l| format!("      {}", l)).collect();
                    format!("|\n{}", indented.join("\n"))
                }
            } else {
                s.clone()
            }
        }
        Value::Number(n) => n.to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Null => "null".to_string(),
        _ => {
            serde_json::to_string(value).unwrap_or_else(|_| "<failed to render value>".to_string())
        }
    }
}

// ---------------------------------------------------------------------------
// Real Terminal implementation
// ---------------------------------------------------------------------------

const SPINNER_FRAMES: [&str; 10] = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];

struct SpinnerState {
    stop: Arc<AtomicBool>,
    handle: JoinHandle<()>,
}

pub(crate) struct Terminal {
    no_color: bool,
    spinner: Mutex<Option<SpinnerState>>,
}

impl Default for Terminal {
    fn default() -> Self {
        Self::new()
    }
}

impl Terminal {
    pub(crate) fn new() -> Self {
        Self {
            no_color: env::var_os("NO_COLOR").is_some(),
            spinner: Mutex::new(None),
        }
    }

    fn style(&self, text: &str, ansi_codes: &[&str]) -> String {
        if self.no_color {
            text.to_string()
        } else {
            format!("{}{}\x1b[0m", ansi_codes.join(""), text)
        }
    }
}

impl TerminalOutput for Terminal {
    fn banner(&self, model: &str, tools: &[ToolName]) {
        let border = |s: &str| self.style(s, &["\x1b[2m"]);
        let tool_list = tools
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        let model_line = format!("model: {}", model);
        let tools_line = format!("tools: {}", tool_list);
        let width = (model.len() + 10).max(tool_list.len() + 10).max(50);
        println!("{}", border(&format!("╭{}╮", "─".repeat(width - 2))));
        println!(
            "{} {:<w$} {}",
            border("│"),
            model_line,
            border("│"),
            w = width - 4
        );
        println!(
            "{} {:<w$} {}",
            border("│"),
            tools_line,
            border("│"),
            w = width - 4
        );
        println!("{}", border(&format!("╰{}╯", "─".repeat(width - 2))));
        println!();
    }

    fn prompt_string(&self) -> String {
        format!("{} ", self.style(">", &["\x1b[1m", "\x1b[36m"]))
    }

    fn thinking(&self, text: &str) {
        let trimmed = text.trim();
        let cleaned = trimmed
            .strip_prefix("THINKING:")
            .or_else(|| trimmed.strip_prefix("thinking:"))
            .map(str::trim)
            .unwrap_or(trimmed);
        if cleaned.is_empty() {
            return;
        }
        for line in cleaned.lines() {
            println!("  {}", self.style(&format!("● {}", line), &["\x1b[90m"]));
        }
    }

    fn tool_call(&self, call: &ValidatedToolCall) {
        println!(
            "  {} {}",
            self.style("CALLING:", &["\x1b[1m", "\x1b[36m"]),
            self.style(&call.name.to_string(), &["\x1b[1m", "\x1b[33m"])
        );
        if let Some(obj) = call.arguments.as_object() {
            for (key, value) in obj {
                println!("    {}: {}", key, format_arg_value(value));
            }
        }
    }

    fn tool_result(&self, result: &ToolResult) {
        let text = result.to_string();
        let is_error = result.is_error();
        let mut lines = text.lines().collect::<Vec<_>>();
        let total = lines.len();
        let hidden = total.saturating_sub(10);
        if total > 10 {
            lines.truncate(10);
        }

        let prefix = if is_error {
            format!("  {}{}", self.style("✗", &["\x1b[31m"]), " ")
        } else {
            format!("  {}{}", self.style("✓", &["\x1b[32m", "\x1b[2m"]), " ")
        };

        let color_line = |line: &str| -> String {
            if is_error {
                self.style(line, &["\x1b[31m"])
            } else {
                self.style(line, &["\x1b[32m", "\x1b[2m"])
            }
        };

        if lines.is_empty() {
            println!("{}", prefix.trim_end());
        } else {
            println!("{}{}", prefix, color_line(lines[0]));
            for line in &lines[1..] {
                println!("    {}", color_line(line));
            }
        }

        if hidden > 0 {
            println!(
                "    {}",
                self.style(&format!("[+{} more lines]", hidden), &["\x1b[90m"])
            );
        }
    }

    fn answer(&self, text: &str) {
        let lines: Vec<&str> = text.lines().collect();
        if lines.is_empty() {
            println!("  {}", self.style("■", &["\x1b[37m", "\x1b[1m"]));
        } else {
            println!(
                "  {} {}",
                self.style("■", &["\x1b[37m", "\x1b[1m"]),
                lines[0]
            );
            for line in &lines[1..] {
                println!("    {}", line);
            }
        }
    }

    fn error(&self, text: &str) {
        println!(
            "  {}",
            self.style(&format!("✗ {}", text), &["\x1b[31m", "\x1b[1m"])
        );
    }

    fn spinner_start(&self) {
        let mut guard = self.spinner.lock().expect("spinner mutex poisoned");
        if guard.is_some() {
            return;
        }

        let no_color = self.no_color;
        let stop = Arc::new(AtomicBool::new(false));
        let stop_clone = Arc::clone(&stop);

        let handle = thread::spawn(move || {
            let mut idx = 0usize;
            while !stop_clone.load(Ordering::Relaxed) {
                let frame = SPINNER_FRAMES[idx % SPINNER_FRAMES.len()];
                let rendered = if no_color {
                    format!("\r  {}", frame)
                } else {
                    format!("\r  \x1b[90m{}\x1b[0m", frame)
                };
                let _ = io::stderr().write_all(rendered.as_bytes());
                let _ = io::stderr().flush();
                idx += 1;
                thread::sleep(Duration::from_millis(80));
            }
        });

        *guard = Some(SpinnerState { stop, handle });
    }

    fn spinner_stop(&self) {
        let mut guard = self.spinner.lock().expect("spinner mutex poisoned");
        let Some(state) = guard.take() else {
            return;
        };

        state.stop.store(true, Ordering::Relaxed);
        let _ = state.handle.join();

        let _ = io::stderr().write_all(b"\r  \r");
        let _ = io::stderr().flush();
    }

    fn goodbye(&self) {
        println!("{}", self.style("goodbye.", &["\x1b[90m"]));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn format_arg_value_simple_string() {
        assert_eq!(format_arg_value(&json!("hello.txt")), "hello.txt");
    }

    #[test]
    fn format_arg_value_multiline_string() {
        assert_eq!(
            format_arg_value(&json!("line1\nline2")),
            "|\n      line1\n      line2"
        );
    }

    #[test]
    fn format_arg_value_number() {
        assert_eq!(format_arg_value(&json!(42)), "42");
    }

    #[test]
    fn format_arg_value_boolean() {
        assert_eq!(format_arg_value(&json!(true)), "true");
        assert_eq!(format_arg_value(&json!(false)), "false");
    }

    #[test]
    fn format_arg_value_object() {
        assert_eq!(format_arg_value(&json!({"a": 1})), r#"{"a":1}"#);
    }

    #[test]
    fn format_arg_value_array() {
        assert_eq!(format_arg_value(&json!([1, 2, 3])), "[1,2,3]");
    }

    #[test]
    fn format_arg_value_null() {
        assert_eq!(format_arg_value(&json!(null)), "null");
    }

    #[test]
    fn format_arg_value_truncates_long_multiline() {
        let lines: Vec<String> = (1..=12).map(|i| format!("line{}", i)).collect();
        let result = format_arg_value(&json!(lines.join("\n")));
        assert!(result.starts_with("|\n"));
        assert!(result.contains("line8"));
        assert!(!result.contains("line9"));
        assert!(result.ends_with("[+4 more lines]"));
    }
}

impl Drop for Terminal {
    fn drop(&mut self) {
        self.spinner_stop();
    }
}
