// Scaffolding: tool schemas + non-exercise tool implementations (write_file, message_user, ask_user, read_board, update_board). Exercise tools live in exercises.rs. Attendees do not edit this file.

use std::{
    fmt, fs,
    path::{Path, PathBuf},
};

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum ToolName {
    ReadFile,
    WriteFile,
    EditFile,
    Shell,
    ListFiles,
    WebFetch,
    MessageUser,
    AskUser,
    ReadBoard,
    UpdateBoard,
}

#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub(crate) struct ListFilesParams {
    #[schemars(description = "Directory path to list")]
    pub(crate) path: String,
    #[schemars(description = "Maximum depth to recurse (1 = immediate children only)")]
    pub(crate) max_depth: usize,
}

impl ToolName {
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::ReadFile => "read_file",
            Self::WriteFile => "write_file",
            Self::EditFile => "edit_file",
            Self::Shell => "shell",
            Self::ListFiles => "list_files",
            Self::WebFetch => "web_fetch",
            Self::MessageUser => "message_user",
            Self::AskUser => "ask_user",
            Self::ReadBoard => "read_board",
            Self::UpdateBoard => "update_board",
        }
    }

    pub(crate) fn from_str(s: &str) -> Option<Self> {
        match s {
            "read_file" => Some(Self::ReadFile),
            "write_file" => Some(Self::WriteFile),
            "edit_file" => Some(Self::EditFile),
            "shell" => Some(Self::Shell),
            "list_files" => Some(Self::ListFiles),
            "web_fetch" => Some(Self::WebFetch),
            "message_user" => Some(Self::MessageUser),
            "ask_user" => Some(Self::AskUser),
            "read_board" => Some(Self::ReadBoard),
            "update_board" => Some(Self::UpdateBoard),
            _ => None,
        }
    }
}

impl fmt::Display for ToolName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl PartialEq<&str> for ToolName {
    fn eq(&self, other: &&str) -> bool {
        self.as_str() == *other
    }
}

impl PartialEq<str> for ToolName {
    fn eq(&self, other: &str) -> bool {
        self.as_str() == other
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ToolResult {
    Ok(String),
    Err(String),
}

impl ToolResult {
    pub(crate) fn is_error(&self) -> bool {
        matches!(self, Self::Err(_))
    }

    pub(crate) fn text(&self) -> &str {
        match self {
            Self::Ok(s) | Self::Err(s) => s,
        }
    }
}

impl PartialEq<&str> for ToolResult {
    fn eq(&self, other: &&str) -> bool {
        match self {
            Self::Ok(text) => text == *other,
            Self::Err(text) => {
                if let Some(stripped) = other.strip_prefix("Error: ") {
                    text == stripped
                } else {
                    text == *other
                }
            }
        }
    }
}

impl fmt::Display for ToolResult {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.text())
    }
}

#[derive(Debug, Clone)]
pub(crate) enum ToolSelection {
    All,
    Only(Vec<ToolName>),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct PermissionResult {
    pub(crate) allowed: bool,
    pub(crate) reason: String,
}

#[derive(Debug, Clone, Serialize)]
pub(crate) struct AuditEvent {
    pub(crate) timestamp: String,
    pub(crate) event: String,
    pub(crate) details: serde_json::Value,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct CheckpointInfo {
    pub(crate) id: String,
    pub(crate) timestamp: String,
    pub(crate) path: PathBuf,
}

pub(crate) struct SkillInfo {
    pub(crate) name: String,
    pub(crate) description: String,
    pub(crate) path: PathBuf,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct CommandPrompt {
    pub(crate) name: String,
    pub(crate) description: String,
    pub(crate) argument_hint: Option<String>,
    pub(crate) path: PathBuf,
}

#[derive(Debug, Clone, PartialEq)]
pub(crate) struct ContextUsage {
    pub(crate) system: usize,
    pub(crate) conversation: usize,
    pub(crate) tools: usize,
    pub(crate) total: usize,
    pub(crate) limit: Option<usize>,
    pub(crate) percentage: Option<f64>,
}

#[derive(Clone)]
pub(crate) struct Tool {
    pub(crate) name: ToolName,
    pub(crate) description: &'static str,
    pub(crate) schema: Value,
    pub(crate) execute: fn(Value) -> ToolResult,
}

#[derive(Debug, Deserialize)]
pub(crate) struct RawToolCall {
    pub(crate) name: String,
    pub(crate) arguments: Value,
}

#[derive(Debug, Clone)]
pub(crate) struct ValidatedToolCall {
    pub(crate) name: ToolName,
    pub(crate) arguments: Value,
}

#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub(crate) struct ReadFileParams {
    pub(crate) path: String,
}

#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub(crate) struct WriteFileParams {
    pub(crate) path: String,
    pub(crate) content: String,
}

#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub(crate) struct EditFileParams {
    pub(crate) path: String,
    pub(crate) line_start: usize,
    pub(crate) line_end: usize,
    pub(crate) old_text: String,
    pub(crate) new_text: String,
}

#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub(crate) struct ShellParams {
    pub(crate) command: String,
}

#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub(crate) struct WebFetchParams {
    pub(crate) url: String,
}

#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub(crate) struct MessageUserParams {
    pub(crate) message: String,
}

#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub(crate) struct AskUserParams {
    pub(crate) question: String,
}

#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub(crate) struct ReadBoardParams {
    pub(crate) path: String,
}

/// Update one phase on a generic kanban board.
#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub(crate) struct UpdateBoardParams {
    pub(crate) path: String,
    pub(crate) phase: String,
    pub(crate) status: String,
    pub(crate) artifact: Option<String>,
}

pub(crate) fn execute_write_file(args: Value) -> ToolResult {
    let params: WriteFileParams = match serde_json::from_value(args) {
        Ok(v) => v,
        Err(e) => return ToolResult::Err(format!("writing file: invalid arguments: {e}")),
    };

    match fs::write(&params.path, params.content) {
        Ok(_) => ToolResult::Ok(format!("Successfully wrote to {}", params.path)),
        Err(e) => ToolResult::Err(format!("writing file: {e}")),
    }
}

pub(crate) fn execute_message_user(args: Value) -> ToolResult {
    match serde_json::from_value::<MessageUserParams>(args) {
        Ok(p) => ToolResult::Ok(p.message),
        Err(e) => ToolResult::Err(format!("invalid arguments: {e}")),
    }
}

pub(crate) fn execute_ask_user(args: Value) -> ToolResult {
    match serde_json::from_value::<AskUserParams>(args) {
        Ok(p) => ToolResult::Ok(p.question),
        Err(e) => ToolResult::Err(format!("invalid arguments: {e}")),
    }
}

pub(crate) fn execute_read_board(args: Value) -> ToolResult {
    let params: ReadBoardParams = match serde_json::from_value(args) {
        Ok(v) => v,
        Err(e) => return ToolResult::Err(format!("invalid arguments: {e}")),
    };

    let board_path = Path::new(&params.path);
    if !board_path.exists() {
        return ToolResult::Err(format!("board not found: {}", params.path));
    }

    match fs::read_to_string(board_path) {
        Ok(content) => match serde_json::from_str::<Value>(&content) {
            Ok(_) => ToolResult::Ok(content),
            Err(e) => ToolResult::Err(format!("reading board: {e}")),
        },
        Err(e) => ToolResult::Err(format!("reading board: {e}")),
    }
}

pub(crate) fn execute_update_board(args: Value) -> ToolResult {
    let params: UpdateBoardParams = match serde_json::from_value(args) {
        Ok(v) => v,
        Err(e) => return ToolResult::Err(format!("invalid arguments: {e}")),
    };

    let board_path = Path::new(&params.path);
    if !board_path.exists() {
        return ToolResult::Err(format!("board not found: {}", params.path));
    }

    let board_content = match fs::read_to_string(board_path) {
        Ok(content) => content,
        Err(e) => return ToolResult::Err(format!("updating board: {e}")),
    };
    let mut board: Value = match serde_json::from_str(&board_content) {
        Ok(value) => value,
        Err(e) => return ToolResult::Err(format!("updating board: {e}")),
    };

    let Some(phases) = board.get_mut("phases").and_then(Value::as_object_mut) else {
        return ToolResult::Err(format!("unknown phase: {}", params.phase));
    };
    let Some(phase_obj) = phases.get_mut(&params.phase).and_then(Value::as_object_mut) else {
        return ToolResult::Err(format!("unknown phase: {}", params.phase));
    };

    phase_obj.insert("status".to_string(), Value::String(params.status.clone()));
    if let Some(artifact) = params.artifact {
        phase_obj.insert("artifact".to_string(), Value::String(artifact));
    }
    board["currentPhase"] = Value::String(params.phase);

    let board_pretty = match serde_json::to_string_pretty(&board) {
        Ok(text) => text,
        Err(e) => return ToolResult::Err(format!("updating board: {e}")),
    };

    if let Err(e) = fs::write(board_path, format!("{}\n", board_pretty)) {
        return ToolResult::Err(format!("updating board: {e}"));
    }

    ToolResult::Ok(board_pretty)
}

pub(crate) fn format_tool_for_context(tool: &Tool) -> String {
    let schema_json =
        serde_json::to_string_pretty(&tool.schema).unwrap_or_else(|_| "{}".to_string());
    format!(
        "### {}\n{}\nParameters:\n```json\n{}\n```",
        tool.name, tool.description, schema_json
    )
}

pub(crate) fn get_enabled_tools(
    config: &crate::config::AgentConfig,
    all_tools: &[Tool],
) -> Vec<Tool> {
    match &config.tools {
        ToolSelection::All => all_tools.to_vec(),
        ToolSelection::Only(enabled_tools) => all_tools
            .iter()
            .filter(|tool| tool.name == ToolName::MessageUser || enabled_tools.contains(&tool.name))
            .cloned()
            .collect(),
    }
}
